### ISSUE TITLE
Unable to stop an alert sound from a notification

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#1]
In 20.1, we make use of `sound` property of `UNNotificationContent` to play alert sounds. The benefits are:

1. It respects System Preferences > Notifications > Due > Play sound for notifications setting.
2. It respects system Do Not Disturb (DND) setting
3. It respects System Preferences > Sound > Sound Effects > Alert volume setting

Compared with the older method of playing alert sounds manually with `AVFoundation`, there is one annoying problem: there is no way to cut an alert midway when it's being played.

This means that users who use long alert sounds will have to wait until the alert sound finish playing. This is unlike in iOS where the alert sound is automatically cut when the user interacts with the notification, or dismisses the notification. We can also programmatically cut the alert sound midway by cancelling the notification with `UNUserNotificationCenter.current().removeDeliveredNotifications()` on iOS, but not on macOS.

This problem afflicts all macOS versions with the new UserNotifications API (namely macOS 10.14, 10.15), including Big Sur (macOS 11). I've filed a bug report with Apple (Clicking on a notification does not stop the alert sound FB7866427 on 8 July 2020), but we should not hold our breath for a fix anytime soon.

In the meantime, we need a solution for users who may be using long alert sounds, because it can be incredibly frustrating to not be able to stop a long alert sound.

**Comment by honcheng** [comment]
https://stackoverflow.com/questions/25210120/is-it-possible-to-turn-on-off-do-not-disturb-for-os-x-programmatically/36385778#36385778

This link here seems to be about changing DND state, not reading it.

**Comment by honcheng** [comment]
https://stackoverflow.com/questions/26311482/programmatically-check-state-of-do-not-disturb-on-os-x/39095105

And the suggested solutions here seem to required opting out of sandbox.

**Comment by junjie** [comment]
One solution would be to revert back to the older `AVFoundation` method of playing alert sound. This would mean we need to find ways to address the advantages that using `UNNotification` to play alert sound can offer. Namely:

1. Respect System Preferences > Notifications > Due > Play sound for notifications setting.
2. Respect system Do Not Disturb (DND) setting
3. Respect System Preferences > Sound > Sound Effects > Alert volume setting

(1) we can do with existing API. (2) I understand there may be some way to do that from my previous research on SO. (3) I'm not sure if we can find that out, but it's the lowest on the priority.

If we can address (1) and (2), we can revert to the `AVFoundation` method of playing alert sounds ourselves, so that we can cut it off when the user interacts with the notification.

**Comment by honcheng** [comment]
> Respect system Do Not Disturb (DND) setting

 https://stackoverflow.com/a/39095105

It's possible to read DND state from UserDefaults:

```
let theDefaults = UserDefaults(suiteName: "com.apple.notificationcenterui")
print(theDefaults?.bool(forKey: "doNotDisturb"))
```

```
let theDefaults = UserDefaults(suiteName: "com.apple.notificationcenterui")
let theDate = Date()
let theCalendar = Calendar.current

let theHour = calendar.component(.hour, from: theDate)
let theMinute = calendar.component(.minute, from: theDate)
let theMinuteOfDay = Double(theHour * 60 + theMinute)

if theMinuteOfDay >= theDefaults.double(forKey: "dndStart") && 
    theMinuteOfDay <= theDefaults.double(forKey: "dndEnd") {
    // ...
}

```
But this solution will only work if we remove 'App Sandbox' capability. But that will mean we can no longer distribute the app in the Mac App Store. In sandbox, it always return false.

**Comment by junjie** [comment]
Ah, in that case, that is no longer workable. I think we can at least support a switch in Preferences for users who would like to continue using long alert sounds to fall back to using the `AVFoundation` method for playing alert sounds, with the trade-offs being that alert sounds cannot respect DND setting nor alert volume setting.

I'm thinking that switch can be somewhere here:

![CleanShot 2020-07-28 at 10 51 52@2x](https://user-images.githubusercontent.com/524420/88618658-3cca0600-d0cc-11ea-9c7f-979b5689cca8.png)

This would be off by default. When the user toggles this switch on, we let them know the trade-offs, and ask them to confirm if that is what they'd like to enable.

The exact wordings of this switch, and the confirmation prompt, I have not thought about. But I think we can work with some placeholder text first?

What do you think?

**Comment by honcheng** [comment]
> I think we can at least support a switch in Preferences for users who would like to continue using long alert sounds to fall back to using the AVFoundation method for playing alert sounds, with the trade-offs being that alert sounds cannot respect DND setting nor alert volume setting.

Let's go with that.

**Comment by junjie** [comment]
My suggestion for the wordings of this option:

**Checkbox title:** Play alert sounds using Due (instead of macOS)

Whenever the checkbox is checked, it should display a prompt:

**Playing alert sounds using Due can allow you to stop them whenever you click on a notification**
A bug in macOS prevents notification alert sounds from being stopped. However, because Due cannot determine your Do Not Disturb status, it will always play alert sounds.

\[Cancel\] \[Play Using Due\]

**Comment by junjie** [comment]
2nd attempt at the prompt:

**You can stop alert sounds played using Due, but alerts will sound even if Do Not Disturb is enabled.**
This setting can work around a bug in macOS that prevents notification alert sounds from being stopped. However, Due is unable to determine your Do Not Disturb setting, and will always play alert sounds.

**Comment by junjie** [comment]
Still kind of verbose, but let's try it and see how it looks?

**Comment by junjie** [comment]
Earlier we also spoke about using Accessibility API to detect state of DND. This is not very ideal because it requires the user to manually give access to Due in System Preferences > Security & Privacy > Privacy > Accessibility. Also, you mentioned the API seems to be limited to just [toggling](https://stackoverflow.com/a/36385778/401329), instead of detecting DND state.

I'm not familiar with the accessibility API at all. But I **think** it can obtain the value using the key like [kAXEnabledAttribute ](https://developer.apple.com/documentation/applicationservices/kaxenabledattribute?language=objc), like how a [window position can be obtained](https://stackoverflow.com/a/53946598/401329).

If that is possible, I think we can work around the issue and continue to respect DND. However, I think that's quite a bit of work, and it's still going to be challenging to communicate this to the user. So we may just KIV this solution to respect DND for now?

**Comment by junjie** [comment]
3rd attempt:

**Do you want to play alert sounds using Due?**
This works around a system bug, allowing you to stop alert sounds when you click on a notification. However, because of system limitations, Due will play alert sounds even if Do Not Disturb is enabled.

[Don't Use] [Use Due To Play Sounds]

**Comment by JonathanAquino** [comment]
IMO this text is misleading because it sounds like if you turn it off, then no alert sounds will happen.

How about:

**Stop alert sounds when you click on a notification?**
This works around a system bug in which alert sounds continue to play after you click on a notification, which can be annoying for long alert sounds. However, because of system limitations, Due will play alert sounds even if Do Not Disturb is enabled if you select this option.

[Don't Use] [Stop alert sounds on click]

**Comment by junjie** [comment]
Thanks @JonathanAquino. Re-reading this, I like your suggestion "Stop alert sounds when you click on a notification?". However I like it more for the checkbox rather than the alert prompt.

My current suggestion for the checkbox ("Play alert sounds using Due (instead of macOS)") doesn't tell people why they'd want to enable that. But if we use what you've suggested for the alert title in the checkbox instead, it'd make more sense.

**Checkbox title:** Stop alert sounds when clicking on a notification

Whenever the checkbox is checked, it should display a prompt:

**Enabling this option allows you to stop long alert sounds, but alerts will play even when Do Not Disturb is enabled. Do you want to continue?** 
This option uses Due to play alert sounds so as to work around a system bug. However, because of system limitations, alerts will play even if you turn on Do Not Disturb.
[Don’t Enable] [Enable]

**Comment by JonathanAquino** [comment]
Sounds good.

**Comment by honcheng** [comment]
<img width="620" alt="Screenshot 2020-08-03 at 4 17 23 PM" src="https://user-images.githubusercontent.com/208827/89161189-db5ed700-d5a4-11ea-8701-aa37e0bd82b6.png">

**Comment by honcheng** [comment]
@junjie This feature is now added, pending localisation
