### ISSUE TITLE
Explore a more monochromatic light theme

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#10]
While many users liked the colour schemes included, some users thought they were too opinionated. I think the darker themes are fine for now, perhaps we could explore a more monochromatic light theme, Vanilla Lilac without the purple accent. #9

**Comment by tedmiston** [comment]
Thank you for adding this.  I really like how minimal the iOS app light and black themes are right now.  If we could have something similar for the macOS app or even a way to tweak color codes like Slack that would be awesome.

**Comment by tedmiston** [comment]
On a related note, if you do implement the custom themes like Slack does, it would be nice to be able to change the font face and font style of the headers.  For me "Overdue", "Today", etc feel huge right now vs I'd prefer they were more subtle, smaller, and faded into the background to focus on todos instead.

**Comment by tedmiston** [comment]
Hi @junjie do you have any updates on having the option for more neutral themes?  Something equivalent to the light and dark themes that the iOS app has today would be great.  Thank you!

**Comment by junjie** [comment]
Hi @tedmiston, no updates on that front at the moment. We've been concentrating on the Big Sur/Apple Silicon work lately.
