### ISSUE TITLE
Snooze directly from notification with postpone setting

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#102]
> a “Postpone” setting where I could postpone something for a set amount (which I could preset in my SETTINGS); here’s what I’d envision:
> 
> a pulldown that had a few choices: 30 minutes, 1 hour, 1 day
> 
> Rather than having to edit the actual event, I think this would be so fast, and I would use it all the time.
> 
> It’d be great if this were doable from a notification on the Mac, or from the notification on the iPhone, without having to go into Due and edit the item…

Related #101

**Comment by vitorgalvao** [comment]
As something to think about when implementing this, I’ve seen this snooze done in two ways.

In Apple Calendar, clicking the snoozing option will do it for a set time and dismiss the notification *but if we click and hold*, we’ll see a dropdown. We can then drag down to the desired snooze time and release the mouse to select it.

In Apple Reminders, clicking the `Later` notification option always presents the dropdown with times for the snooze. Clicking and holding also works, but isn’t necessary.

**Comment by junjie** [comment]
Thanks Vitor for the comparison. I've not studied the API in-depth at this point, but IIRC, the API doesn't allow us to do it Calendar way. So I remembered not considering this feature in the past because it makes the Mark Done button tougher to get to.

**Comment by aleks-fill** [comment]
It would be very convenient if it was possible to snooze reminders through notifications. Thanks a lot in advance!

If it helps, the GoodTask app (https://goodtaskapp.com/) has this functionality.
<img width="355" alt="Screenshot 2020-11-12 at 23 54 00" src="https://user-images.githubusercontent.com/3996988/98995945-2a70bc80-2543-11eb-8659-10cfa044e518.png">
But I like your app better😇. I mean, in principle, it is possible to implement such functionality.
