### ISSUE TITLE
Icon badge mode like iOS

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#108]
Option to badge icon like iOS, with overdue only, today+overdue, etc.

**Comment by junjie** [comment]
> In both the iPad and iPhone I do get a count of the overdue items in the icon, not so in the Mac. I do not seem to find a way to turn that on

**Comment by junjie** [comment]
> Any chance you could add back the badge notification in MacOS for overdue items? I think it used to show how many due items as a badge notification, but no more. Seems like a missing feature (I miss it!)

**Comment by gitstua** [comment]
This has been done so can be closed 🎉
