### ISSUE TITLE
Location reminders

### ISSUE THREAD

**Issue by rben01** [dueapp/Due-macOS#110]
I know the readme says that location reminders do not fit into the overall vision of Due, but... why not? They're a very useful kind of reminder, and if they went in their own list in the side panel (with time-based reminders and timers) then you'd hardly notice them in the app UI.

**Comment by junjie** [comment]
GPS limitations means they're not as reliable as we would want them to be, especially in areas with poor GPS reception. Also, there's a lot more we can do for time-based reminders, and supporting location-based reminders means take up a big portion of our development resources to make that happen.
