### ISSUE TITLE
Snoozing on iOS leads to repeating "X was snoozed" reminder on macOS

### ISSUE THREAD

**Issue by Arnoud-B** [dueapp/Due-macOS#112]
When I snooze items on iOS, I get a reminder of it on macOS (correct). However, I keep getting this reminder at the repeat interval of the item. I should only get the "item was snoozed" reminder once.

**Comment by junjie** [comment]
Are you able to provide me with the screenshots of the notifications you're referring to so I have a better idea what's the issue?

**Comment by Arnoud-B** [comment]
Sure, here's a screenshot: https://jmp.sh/DaPtfvG

![main_full](https://user-images.githubusercontent.com/524420/97134922-c3ed4f80-1789-11eb-94bc-0bf9761e9763.jpg)

To test, I snoozed several reminders with different repeat intervals planned at the same time from my iPhone. On macOS, it keeps reminding me that they were snoozed at the repeat interval defined for each reminder.

**Comment by Arnoud-B** [comment]
It seems there is another error which may be related: After I clicked "Mark Done" on the notification, it said 2 reminders were modified in a notification directly after that (3 reminders were sending notifications that they were snoozed at the repeat interval). I did not touch those reminders yet they were modified by completing one of the 3 reminders..

**Comment by junjie** [comment]
> Sure, here's a screenshot: https://jmp.sh/DaPtfvG
> To test, I snoozed several reminders with different repeat intervals planned at the same time from my iPhone. On macOS, it keeps reminding me that they were snoozed at the repeat interval defined for each reminder.

Thanks for the screenshot. The notification you're getting is an auto snooze notification. It results from an item being overdue and having an auto snooze applied to it. You'll receive a notification at the auto snooze interval repeatedly until you turn off auto snooze for the item, postpone the item, or mark it complete. 

It is not a notification telling you that you have "snooze" the notification somewhere. On that note, earlier you mentioned "When I snooze items on iOS". I assume now that you mean you have postponed the reminder on iOS, and you were thinking that this notification on your Mac is telling you that you have snoozed the item on your iPhone?

**Comment by junjie** [comment]
> It seems there is another error which may be related: After I clicked "Mark Done" on the notification, it said 2 reminders were modified in a notification directly after that (3 reminders were sending notifications that they were snoozed at the repeat interval). I did not touch those reminders yet they were modified by completing one of the 3 reminders..

This notification about "N reminders modified" is appearing on your Mac? 

This happens after a sync, if you have "Sync completed with changes" notification enabled in Due > Preferences > Notifications. This is off by default.

This probably just means that before you made the change on your Mac, Due Mac has not synced in any changes you have already made on another device. After you made the change on your Mac, Due attempted to upload the changes, but found unsynced changes made on another device, synced them (resulting in the 2 reminders modified), before uploading the new changes.

**Comment by Arnoud-B** [comment]
OK, so it's a wording & sync issue? I don't remember ever seeing a "Reminder snoozed" notification on iOS. After the snooze period, it just shows the reminder again. I would just expect "Reminder" or "Reminder still due" as the title on macOS, coming back at the auto-snooze interval, as the goal of the app is to remind me there is still a reminder due, not to remind me that it snoozed a reminder (which is the action I took on the iOS device, so confusing).

Indeed I notice that macOS is not syncing unless I do it manually.

**Comment by junjie** [comment]
I see, I see how it can be confusing. The idea was to differentiate the notifications based on whether this reminder just became due, or when it fires again because it was auto snoozed. We'll keep this in mind to see if this needs adjustment in future. Thank you!
