### ISSUE TITLE
First suggestion of "Saturday 08:00", "Saturday 8am" is "Tomorrow 8am"

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#114]
![PastedGraphic-1](https://user-images.githubusercontent.com/524420/96817200-69828500-1451-11eb-92dd-51a0b87ed92c.png)

> Why is the better match to what I typed the second choice?
> 
> I keep typing, hitting return and realizing it got postponed to tomorrow instead of the day I specified.

**Comment by mrw** [comment]
Hello! I'm not sure if you prefer comments or just 👍 on the original posts, but I'm noting here that this is something I'd love to see fixed also. It impacts me quite a bit when managing the to-dos from my computer. Usually it's when I'm delaying things by a couple of days so want to write something like "Sunday 7am", but the first option in the dropdown becomes "tomorrow 7am."

**Comment by junjie** [comment]
This is fixed, slated for 21.5
