### ISSUE TITLE
Enable Reminders > Auto Snooze menu when editor is visible

### ISSUE THREAD

**Issue by mrehler** [dueapp/Due-macOS#115]
I’ve customized a Due shortcut through macOS to have "Auto Snooze > Every Minute" and "Auto Snooze > Every 5 Minutes” so that I can quickly switch between the two. It would make for a much more convenient flow if these menu items were functional in the New Item mini-window and using these shortcuts was able to change these parameters on a new reminder.

**Comment by junjie** [comment]
Thanks, make sense, we'll look into enabling the menu items when the editor is present:

![CleanShot 2020-10-26 at 13 05 10@2x](https://user-images.githubusercontent.com/524420/97135664-e2544a80-178b-11eb-87c4-017121345e1b.png)

**Comment by junjie** [comment]
Done and slated for 20.9.
