### ISSUE TITLE
New reminder window that can be triggered with hotkey to add a reminder without bringing Due's main window up

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#117]
> • Related to the prior few suggestions, it seems crazy that there is no universal global keystroke shortcut option to create a new reminder, without losing the current app’s focus.

**Comment by junjie** [comment]
> One thing I miss however is the ability to bring up a "New reminder" page with a single key command, no matter which app I'm currently using - it's a very fast way of capturing action items and reminders.
> 
> At the moment, there is only a show/hide Due key command, which then requires a further command to create a new reminder.
> 
> Please consider adding a "create new reminder" key command for quick reminder creation.
>

**Comment by honcheng** [comment]
Feature is implemented and should be out in the next update 21.5
