### ISSUE TITLE
Search results section header should not be collapsible (shouldn't have disclosure triangles); clicking on results section header crashes the app

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#119]
![CleanShot 2020-11-20 at 11 03 14@2x](https://user-images.githubusercontent.com/524420/99753292-f425d500-2b20-11eb-9dc2-c15428cab328.png)

**Comment by honcheng** [comment]
Yes, it should not have a disclosure triangle. Seems you are in a strange in-between state.
Will need to find ways to reproduce it first. 

<img width="284" alt="CleanShot 2020-11-26 at 12 29 48@2x" src="https://user-images.githubusercontent.com/208827/100308342-1d43db00-2fe3-11eb-82ff-ac4f4eac1481.png">

**Comment by junjie** [comment]
@honcheng: Note you don't have to have the disclosure triangle showing to reproduce the crash. Just click on the the section title will do.

Once you do that and it crashes, the next time you do a search the disclosure triangle will be present for Results section.

**Comment by honcheng** [comment]
Thanks. The fix will be out in 20.9
