### ISSUE TITLE
Last cell of table view has non-rounded corner at the bottom

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#121]
![CleanShot 2020-11-25 at 13 24 35@2x](https://user-images.githubusercontent.com/524420/100186882-dcd05880-2f21-11eb-995c-ba11d0e65ae5.png)
![CleanShot 2020-11-25 at 13 24 12@2x](https://user-images.githubusercontent.com/524420/100186884-dd68ef00-2f21-11eb-909c-f365ed5f840f.png)

**Comment by honcheng** [comment]
Fixed is done, will be out in 20.9
