### ISSUE TITLE
Title of reminder can be missing in the table view sometimes

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#122]
![Screen Shot 2020-11-23 at 15 52 36](https://user-images.githubusercontent.com/524420/100196106-5faddf00-2f33-11eb-9ef2-8c888112dcfd.png)

>  Due Mac 20.8 (6536) on MacBookAir7,1 (10.15.7)
>  en_US (English (United States))

@honcheng I remember seeing this bug before, that I thought we'd fixed due to some caching issue? Any recollection?

**Comment by junjie** [comment]
Another user:

![Bildschirmfoto 2020-11-23 um 20 59 04](https://user-images.githubusercontent.com/524420/100196662-275ad080-2f34-11eb-9fad-98e31fcbdd52.png)

20.8 (6536) on Mac OS X 10.14.6

Seems like both are on 20.8, one on Mojave, one one Catalina. Both using 24-hour time.

@honcheng Given that the reports about this came in after 20.8, could it have been changes for the Big Sur update for pre-Big Sur machines?

**Comment by honcheng** [comment]
@junjie The cache clearing was not working as expected. Likely not due to Big Sur. But it should be fixed in 20.9.
