### ISSUE TITLE
Open at login still does not hide window by default

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#124]
> Can you check if 20.8 addresses this issue?

Issue is still there.

Due Version 20.8 (6536)
macOS 10.14.6 (18G6032)

_Originally posted by @vitorgalvao in https://github.com/dueapp/Due-macOS/issues/39#issuecomment-726739459_

**Comment by junjie** [comment]
Seems to be related to entitlements issues. Working on fix again. Sorry about that.

**Comment by junjie** [comment]
Tested and confirmed fixed.

**Comment by junjie** [comment]
@vitorgalvao, can you try 20.9 from the App Store? I hope we finally nailed it this time!

**Comment by vitorgalvao** [comment]
It works!

Though the solution is unconventional. You’re really opening Due as an hidden app (icon in Dock is transparent, same as <kbd>⌘</kbd><kbd>H</kbd>) as opposed to without any windows (icon is opaque, same as <kbd>⌘</kbd><kbd>W</kbd>).

But I’ll take it! Only did very brief testing and it seems to work well. Thank you for keeping at it. I’m really satisfied with your responses on this issue tracker, even, thumbs up for the good work and effort spent, it’s appreciated.

**Comment by junjie** [comment]
Thanks for confirming, and for the patience while we worked through this issue!
