### ISSUE TITLE
Add themes that do not use serif fonts

### ISSUE THREAD

**Issue by NewsGuyTor** [dueapp/Due-macOS#126]
I'm not a fan of the new design as it currently stands, but thankfully it can be fixed to look good quite easily.

The first issue is likely a bug. Because the grey color of the search box and the grey color of a selected task are quite close, yet noticeably different, it just looks sloppy. They either need to be more different or identical. 

Personally I would make the search box a much lighter grey than it is now, it looks quite menancing with its darkness now. Even better, in my opinion, would be to hide it until you scroll up to see it.

The serif font for the day looks quite bad in my opinion. It looks off since you generally don't see serif fonts in UI text on macOS, and it looks extra bad since it's not properly sized (the 7 in 17 is way larger than the 1, for example). San Fransisco would look much better in my opinion. An option for changing the font could be an easy thing to implement in order to inzentivize updates.

I'm not a fan of the only light theme either, Vanilla Lilac. Please add a neutral theme, preferably one with a [standard grey translucent sidebar using Behind-window blending.](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/translucency/)

**Comment by vitorgalvao** [comment]
> I'm not a fan of the new design as it currently stands, but thankfully it can be fixed to look good quite easily.

Those are different things. Not being a fan doesn’t mean it needs fixing. As a designer, I have no major qualms with the new looks, nor do a bunch of other people.

> Because the grey color of the search box and the grey color of a selected task are quite close, yet noticeably different, it just looks sloppy.

“Sloppy” is too strong of a word. It’s a minor thing. Though I don’t disagree with making them look stand out more from each other.

> I would make the search box a much lighter grey than it is now, it looks quite menancing with its darkness now.

It’s a neutral grey, nothing menacing I can feel from it.

> Even better, in my opinion, would be to hide it until you scroll up to see it.

That would be a huge bump down in usability. People are complaining of [the loss of usability in Apple hiding the proxy icon](https://mjtsai.com/blog/2020/10/05/big-surs-hidden-document-proxy-icon/) and your suggestion is essentially the same. There’s no benefit to hiding an element whose space when hidden wouldn’t be used.

> The serif font for the day looks quite bad in my opinion.

In mine, it looks fine. Not amazing, not awful.

> It looks off since you generally don't see serif fonts in UI text on macOS

Not every interface needs to look the same. This is text you don’t interact with, and being in a different typeface makes it clear it’s a different thing.

> and it looks extra bad since it's not properly sized (the 7 in 17 is way larger than the 1, for example).

No, it is not improperly sized, [it’s a feature of the typeface](https://en.wikipedia.org/wiki/Text_figures).

It’s fine to dislike the way an application looks and ask for alternatives, but claiming those choices are bugs that need “improvement” and “fixes”—as if they affect everyone in the same manner they bother you—is dismissive of the choices made by the developers. You may disagree with the selections made for the themes, but that doesn’t make them wrong.

**Comment by NewsGuyTor** [comment]
What a pedantic response. Would "Improve typography and design for the people who dislike the current theme" really be a better title in your opinion? You don't really have to respond, I'm not interested in a pedantical lingustic debate.

Obviously I'm writing my opinions. And I'm not the only one who would like a new theme that fits more with common macOS interface standards, according to the Mac App Store reviews the current one is very divisive. 

Multiple reviews call it ugly, and since fixing that for us is quite simple it should be implemented.

**Comment by jjlharrison** [comment]
I don't see anything pedantic about the response from @vitorgalvao. I certainly agree with not needlessly hiding interface elements, we not exactly talking about an app that is being used on small screens.

Sure, there are improvements that can be made, but there is nothing offensive or particularly broken as far as I can see.

It's an opinionated design, there will always be people that don't like it and you cannot cater to everyone's tastes.

**Comment by NewsGuyTor** [comment]
The whole point of themes is to cater to different tastes. 

I also disagree with your point about small screens. My Macbook 12' is 900 pixels heigh, now just one notification takes up more than half the screen height. This is my full screen height.
<img width="419" alt="2020-12-17 kl  21 23 40" src="https://user-images.githubusercontent.com/19603024/102540084-d19ac380-40ae-11eb-820b-c32ea3f36be2.png">


Since I usually have less than 10 notifications the search box is just visual clutter. The best option would probably be to add a checkbox in Preferences to hide it for those who don't need it.

**Comment by vitorgalvao** [comment]
> Would "Improve typography and design for the people who dislike the current theme" really be a better title in your opinion?

If that’s what you took from my reply, you didn’t understand it. Naturally, I may share the blame for not having been sufficiently clear. In addition, in rereading I do see how my last paragraph in particular can be taken as aggressive or dismissive, but rest assured that wasn’t my intention and I apologise for seemingly having ticked you off—I take no pleasure in annoying people. I strive to read online communication as if it were written positively and sometimes assume (wishfully hope?) others will do the same.

> Multiple reviews call it ugly, and since fixing that for us is quite simple it should be implemented.

Are we sure it’s simple? I’m really asking; I don’t know how Due’s team implements themes, but there must be a reason why they haven’t yet added more if a lot of reviews are against it. It probably takes more effort than assumed.

I was hoping we could still salvage this discussion, but you’re giving yourself thumbs up on all of your posts (are you aware GitHub informs of who gave a reaction?), which I see no reason to other than to artificially inflate agreement, and that isn’t conductive to arguing in good faith.

So I’ll direct my apologies to the Due developers for having to read an unproductive discussion, and wish you all a genuinely good weekend.

> I don't see anything pedantic about the response from @vitorgalvao.

Thank you for confirming my original answer can indeed be interpreted as it was intended.

**Comment by NewsGuyTor** [comment]
> > Multiple reviews call it ugly, and since fixing that for us is quite simple it should be implemented.
> 
> Are we sure it’s simple? I’m really asking; I don’t know how Due’s team implements themes, but there must be a reason why they haven’t yet added more if a lot of reviews are against it. It probably takes more effort than assumed.

The font is really easy to change, it's only font files that can be found in the application resources. It can't be that hard to change the colors to something neutral either, that's what themes are for. Implementing proper translucency would obviously be harder, but I think it would be worth it :)

> isn’t conductive to arguing in good faith.

I didn't come here to argue in the first place.

**Comment by rben01** [comment]
I for one really like the new UI, especially the serif font. Considering how sparsely it's used throughout the UI (just the section headings, right?) It's just the right amount of quirky.

For the search bar, I could see the sidebar between the timers and the logbook being a more appropriate place for it.

**Comment by junjie** [comment]
Thanks for the suggestions. Thank you @vitorgalvao @jjlharrison @rben01 for taking time to provide your valuable feedback.

I've split @NewsGuyTor suggestions into 3 issues: #126 #131 and #132, renaming this specifically to address the complaint for serif font.

**Comment by NewsGuyTor** [comment]
Awesome, but I think it would be best to add a seperate option for type of font, seperate from the theme. That way users can get the combination they like the best between serif, sans-serif, purple, dark mode, neutral etc.
