### ISSUE TITLE
Add Critical Alerts

### ISSUE THREAD

**Issue by NewsGuyTor** [dueapp/Due-macOS#127]
Please add the option of sending [Critical Alerts](https://developer.apple.com/documentation/usernotifications/unnotificationsettings/2963116-criticalalertsetting) notifications to Due (all platforms). Critical Alerts are notifications that bypass Do Not Disturb and Mute, pretty handy.

Critical Alerts require a special entitlement from Apple, but it should be pretty easy to get since all notifications sent by Due are spesifically created by its users. Make sure to mention that in [the entitlement application](https://developer.apple.com/contact/request/notifications-critical-alerts-entitlement/).

**Comment by NewsGuyTor** [comment]
Perhaps you could mention that users set medication reminders using Due, that may ease approval.

**Comment by junjie** [comment]
This is now available for Due 23.3 on iOS. Critical alerts entitlements are not currently available for macOS, so we'll be closing this until things change.
