### ISSUE TITLE
Window unexpectedly resizes when attached to menu bar

### ISSUE THREAD

**Issue by NewsGuyTor** [dueapp/Due-macOS#128]
The size of the menu bar window should fit the content. Now it fills up more than half my screen height depite it only having one notification, which looks quite pointless:

<img width="468" alt="2020-12-17 kl  17 47 04" src="https://user-images.githubusercontent.com/19603024/102517302-2a0e9880-4090-11eb-9fc4-5bb07dd96744.png">

**Comment by junjie** [comment]
The size of the window is the size that you have Due adjusted to before docking it to the menu bar.

A user would usually have reminders of differing text length, some long and some short. If the window automatically adjusts its width to fit content, it would unexpectedly resize as a user completes/deletes reminders in the list.

Besides, I'm not aware of any macOS app that resizes itself in this manner. As such I don't think this is something we'll be considering.

Thanks for your suggestion.

**Comment by NewsGuyTor** [comment]
Your first statement isn't correct in my case, my docked menu bar window becomes much bigger than the size the window was before it was docked:

https://streamable.com/yt6mhm

I'm not saying it should update dynamically as soon as it changes anyway, just that the initial size should fit the content that existed when the window was opened. BusyCal for example does it like that. 

As you can see now one item takes up more than half the screen.

**Comment by junjie** [comment]
Thanks @NewsGuyTor for the video. The behaviour in your video is not expected and we'll look into it.

**Comment by honcheng** [comment]
Managed to reproduce the bug with the help of the video. The fix will be out in the next update. Thanks
