### ISSUE TITLE
Shortcut to toggle Show/Hide window should actually hide Due app like Cmd-H does, making the next app active

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#13]
https://twitter.com/_jacobsa_/status/1288302830843912192:

> Aaron Jacobs
> @_jacobsa_
> @dueapp
>  Bug report for the redesign: when I press my keyboard shortcut to make it hide again it takes me back to the previously active app, but the previously active window doesn't have focus anymore. This is quite disruptive; I can't use Due without the mouse anymore.

It seems like the shortcut to Show/Hide window only hides Due window, but not the app itself.

Let's see if this can make 20.2? If not, 20.3

**Comment by junjie** [comment]
Workaround: Use Cmd-H to hide window for now.

**Comment by honcheng** [comment]
The fix will be available in 20.2. It will toggle app visibility instead of window visibility in that update. 
Tapping on the menu bar icon will also do the same.
