### ISSUE TITLE
Bulk editing of due date not persisted to disk and lost on relaunch in some circumstances

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#133]
If there are N reminders with different due dates, where N is more than 1, and you attempt to bulk change the due date of all of them to reflect the due date that is the same as one of the reminder being bulk edited, Due will not persist the changes to disk. Due also fails to animate the changes of such a date change.

**Comment by honcheng** [comment]
Found the problem. It's fixed, and will be available in the next update.
