### ISSUE TITLE
Experiment with new postponing behaviour to prevent selection from changing (and list from scrolling)

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#134]
Using the postpone by 10 mins/1 hour/1 day menu options (and its keyboard shortcuts) will attempt to preserve the selection so that the user can continue postponing the same item(s) if needed (e.g. Cmd-+ 3 times to postpone by 30 mins).

However this has the effect of scrolling the list, which may not be desirable. At the same time, using the postpone options multiple times in succession is only something that makes sense with the keyboard shortcuts, and not via the context menu.

As such there are two things that should be done here.

1. For postponing through context menu, we can stop changing the selection (and thus stopping the list from scrolling). The behaviour for the next selection should be similar to what happens after editing the due date of a reminder and saving it (which I believe is to maintain it near to the last selection).
2. As for allowing user to postpone an item multiple times in succession with keyboard shortcut while addressing the scrolling issue, we can delay the actual postponing (with a time-out of perhaps 0.5-1 second). Details below.

Whenever a user postpone an item with keyboard shortcut, we show in a popover the total time that the item(s) will be postponed by, along with the final due date of the item(s). Before the time-out is over, the user can continue to use any combination of the keyboard shortcut to add on to the total time that the item(s) will be postponed by. The user can also cancel the postponing with the Esc key, or immediately postpone the item before the time-out is over with the Return key.

When the time-out is over, or when the user chooses to immediately postpone the item with the Return key, the item gets postponed, while the selection behaviour will mirror what happens after editing the due date of a reminder and saving it (which I believe is to maintain it near to the last selection).

(2) would take more work, so we can at least prioritise (1).

**Comment by honcheng** [comment]
> For postponing through context menu, we can stop changing the selection (and thus stopping the list from scrolling). The behaviour for the next selection should be similar to what happens after editing the due date of a reminder and saving it (which I believe is to maintain it near to the last selection).

Got it. Same behaviour as bulk editor.

**Comment by honcheng** [comment]
> Whenever a user postpone an item with keyboard shortcut, we show in a popover the total time that the item(s) will be postponed by,...

When there are multiple items selected, where do you propose showing the popover?

**Comment by junjie** [comment]
> > Whenever a user postpone an item with keyboard shortcut, we show in a popover the total time that the item(s) will be postponed by,...
> 
> When there are multiple items selected, where do you propose showing the popover?

I'd try attaching to the first visible cell of the selection?

**Comment by honcheng** [comment]
Instead of a popover, what if it is displayed inline, using existing date label but formatted differently to indicate transition state. So this can be displayed in all selected rows. 

Have not thought this through properly, just throw it out for discussion.

**Comment by junjie** [comment]
That sounds like another possibility.

Back in Due 1 for iOS, the implementation was similar:

![](https://www.dueapp.com/assets/img/blog/2020/04/due-1-5-quick-panel.png)

The user can tap on the last three buttons any number of times to postpone an item. The postponing would not take effect right away, but after a time-out. The reminder cell would however update to reflect the new due date. After the time-out, the cell gets moved to the correct position.

This led to two problems, IIRC:

1. Some users found the timeout too fast (though this is not unique to your inline suggestion; would also apply to the popover idea)
2. More importantly, the data model backing the table view became inconsistent for a short period of time. For most cases this wouldn't pose a problem, but eventually there was quite a number of crashes that I suspect resulted from this inconsistency. I was quite glad to get rid of this postponing behaviour in Due 2 for iOS.

The last consideration would be, would it be more obvious to the user the total amount of time to be postponed if it's displayed inline vs a popover?

**Comment by junjie** [comment]
> 1. Some users found the timeout too fast (though this is not unique to your inline suggestion; would also apply to the popover idea)

For the timeout issue, I suspect there may be users who would want the postponing to be immediate, and those who would prefer a longer time-out than what we set.

So I suggest the timeout be read from a preference value where 0 can disable the delay, if that is to be supported in future.

**Comment by honcheng** [comment]
> More importantly, the data model backing the table view became inconsistent for a short period of time. For most cases this wouldn't pose a problem, but eventually there was quite a number of crashes that I suspect resulted from this inconsistency. I was quite glad to get rid of this postponing behaviour in Due 2 for iOS.

> The last consideration would be, would it be more obvious to the user the total amount of time to be postponed if it's displayed inline vs a popover?

How about a HUD? Popover's arrow need to point somewhere. Would it be misleading to point to the top most selected row. If HUD, it'll be floating in the center.

**Comment by junjie** [comment]
HUD sounds possible. The behaviour of how sheets behave in Big Sur feels appropriate? Though I think we shouldn't use sheets since it'd look not too nice on pre-Big Sur Macs

<img width="813" alt="CleanShot 2021-01-04 at 14 17 00@2x" src="https://user-images.githubusercontent.com/524420/103506396-9282b580-4e97-11eb-8c58-80692928608d.png">

> Redesigned sheets
> Sheets in apps have been completely redesigned, removing borders and bezels to put the focus on your content. They automatically dim the background and scale into the centre of the app.

**Comment by honcheng** [comment]
I agree. I’m not thinking of any built-in overlay.
Just a simple translucent view, similar to the holding down CMD key with a
physical keyboard in iPad. What do you think?

**Comment by junjie** [comment]
I actually think something like the Big Sur sheet design feels more appropriate than a dark translucent overlay.

Reason being that we probably should have two buttons within the sheet. One to cancel, one to postpone immediately (before the time-out). Of course, we can also support such a functionality without displaying the button (Esc to cancel, Return to postpone immediately), though it'd be less obvious.

Having buttons on a translucent overlay would feel wrong.

**Comment by honcheng** [comment]
Oh. Misunderstood you. If we use sheets, once the sheet is displayed, the sheet will be the one monitoring subsequent key strokes. That is fine.
