### ISSUE TITLE
Include option for "Alert sound" for defaults for new reminder + breaking out appearance into its own preference pane

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#136]
The iOS version of Due includes an option as to whether new reminders are created with alert sound:

![IMG_C509C01B3ADB-1](https://user-images.githubusercontent.com/524420/104871126-3b93da80-5985-11eb-90d3-8af4a8a66f4b.jpeg)

However the macOS version does not (only options for default due date and auto snooze):

![CleanShot 2021-01-18 at 12 04 29@2x](https://user-images.githubusercontent.com/524420/104871180-5c5c3000-5985-11eb-8f5a-1ed11aec8fbf.png)

Adding another option for this in the General pane makes the General pane a bit too tall, and I think we can start breaking out the appearance setting into its own Appearance pane. My suggestion for how to add the alert sound option, and how to break out the appearance option as follows:

![CleanShot 2021-01-18 at 11 45 25@2x](https://user-images.githubusercontent.com/524420/104871315-b52bc880-5985-11eb-83c1-3c6dca16ce29.png)

This would mirror how Pages does the defaults for new documents with a label "For New Documents":

![CleanShot 2021-01-18 at 11 54 33@2x](https://user-images.githubusercontent.com/524420/104871352-cd9be300-5985-11eb-9d45-2d1425cbca84.png)

**Comment by honcheng** [comment]
Done. Over to @junjie for the final tweaks.
