### ISSUE TITLE
App launches in dark mode after booting up in light mode

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#137]
> I have set the app’s theme to change according to the macOS auto dark/light mode. However, when the app launches after boot (I have set it to launch automatically after login), it will default to the last used setting (usually in dark mode, as I shutdown my Mac during the night). So when I start my Mac in the morning, the app launches in dark mode and does not seem to check the current mode set in the OS.
> 
> A workaround is to manually switch to dark mode in macOS settings and then set it back to automatic, that fixes the issue temporality until the next shutdown.

I can't seem to reproduce this by just quitting the app while system is in dark mode, then changing system theme before launching the app.

So perhaps it has something to do with shutting down and perhaps the OS restoring the last state.

**Comment by junjie** [comment]
> Due Mac 21.0 (6603) on MacBookPro15,2 (11.1.0)
> PrefAttachedToMenuBar = 0
> PrefContentSize = 0
> PrefThemeChangeWithSystem = 1
> PrefThemeChangeWithSystemAutoDarkTheme = Slate Dark
> PrefThemeChangeWithSystemAutoLightTheme = Vanilla Lilac
> PrefThemeName = Slate Dark
> SysUIStyle = 2

**Comment by honcheng** [comment]
Managed to reproduce this issue. A fix will be out in the next update.
