### ISSUE TITLE
Option to disable notifications for sync updates

### ISSUE THREAD

**Issue by geeksam** [dueapp/Due-macOS#138]
I sync Due between my Mac and iPhone, and have the WatchOS app installed as well.  When I add/edit/delete any reminders on the Mac, my wrist buzzes 5-10 seconds later with a notification about the update, and I'm like "YES I KNOW I WAS THERE YOU DON'T HAVE TO TELL ME GAH"

I use Due because I have ADHD, and the iOS reminders were insufficiently annoying to get me to do stuff.  So it feels a bit odd to be complaining that Due's reminders are *too* annoying, since that's why I bought it... but can you please let me turn this one off?  :)  It's getting to the point where I'm hesitating to make changes because I know my watch is going to "helpfully" interrupt me.

**Comment by junjie** [comment]
Hi Sam, you can turn that off in settings following the steps here: https://dueapp.zendesk.com/hc/en-us/articles/360035936832-Turn-off-reminders-added-modified-removed-notifications-after-syncing-in-background

**Comment by geeksam** [comment]
I... would not have guessed that that was what that meant.  Thanks for the pointer!
