### ISSUE TITLE
Using Keyboard Maestro to invoke "Postpone by 10 minutes" etc shortcut crashes app

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#139]
This is probably related to the work done in #134. A user attempted to map another shortcut to trigger the postpone by 10 minutes function in Due using keyboard maestro. Doing so always crashes the app. I can reproduce it on my end.

![CleanShot 2021-02-03 at 14 25 18](https://user-images.githubusercontent.com/524420/106845903-da8b3700-66e6-11eb-9b78-4d875f102e61.png)

**Comment by honcheng** [comment]
The fix for the crash will be out in the next update
