### ISSUE TITLE
Minimize the Due window to the status menu

### ISSUE THREAD

**Issue by parhamdoustdar** [dueapp/Due-macOS#140]
Right now, when I open Due, its window stays around when I press Command-tab. However, I don't need the Due window around at all.

A suggestion that I had is to have the Due window disappear, and show a Due icon in the status menu. If I need the window, I'll call it up with the keyboard shortcut, and if I press the keyboard shortcut again, I'd expect this to disappear into the status menu again.

Examples of apps that do this are Dropbox and 1Password.

**Comment by vitorgalvao** [comment]
Preferences → General → Show icon in: (Menu Bar Only).

**Comment by junjie** [comment]
Thanks @vitorgalvao. Hope this helps @parhamdoustdar, please reopen this if not

**Comment by parhamdoustdar** [comment]
Thanks, I had missed that preference. It works! 😍
