### ISSUE TITLE
Add confirmation prompt when deleting (recurring) reminders (either by long-swipe gesture or keyboard shortcut)

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#142]
There were sporadic reports of recurring reminders going missing on iOS in the past.

It was difficult to track down for sure what had happened to these recurring reminders, given that by the time the user reports this issue we have no idea how long ago these reminders have been removed, but a guess I had was that it was accidentally long-swiped deleted instead of short-swiped marked done.

The safeguard added on iOS was a confirmation prompt when attempting to delete a recurring reminder via long swipe gesture. I also added the ability to turn off long-swipe gesture on iOS in Settings:

![IMG_2720](https://user-images.githubusercontent.com/524420/107177356-9eb8e000-6a0c-11eb-94cc-2d2419597cee.jpg)
![IMG_2721](https://user-images.githubusercontent.com/524420/107177358-a082a380-6a0c-11eb-8c25-bb3b564b5e72.jpg)

I realised that on macOS there is no form of confirmation prompt for long-swipe gesture to delete. Also the keyboard shortcut Delete is pretty easy to trigger too. I think we should add some safeguards here to prevent recurring reminders from being deleted without confirmation.

As for why the safeguard only applies to recurring and not single-use reminders, the thinking is that the impact of accidentally long-swiping to delete (instead of short-swiping to mark done) a single-use reminder is minimal (we just don't see it in the logbook) compared with accidentally deleting a recurring reminder (we'll never get the next instance of it).

**Comment by honcheng** [comment]
Done. Confirmation prompt will be shown when deleting single recurring reminder in 21.2
