### ISSUE TITLE
No reminder text on the extremely bright background when using long touch action on a notification

### ISSUE THREAD

**Issue by romanrev** [dueapp/Due-macOS#144]
It seems to be introduced by the latest App Store update, please have a look at the screenshot
![IMG_2512193D6C58-1](https://user-images.githubusercontent.com/2794589/108287606-2954c880-71df-11eb-964a-603ece7cb4cf.jpeg)

I am on the iOS 14.4, using Dark Theme

**Comment by junjie** [comment]
@romanrev  This is a known iOS 14 bug. Resolution is available here: https://dueapp.zendesk.com/hc/en-us/articles/360055950791-Notification-snooze-buttons-gone-missing

Also, this page is for macOS issues. For iOS support, visit https://dueapp.zendesk.com/hc/en-us/categories/200306449-Due-for-iOS-watchOS or email support within app Help > Email.
