### ISSUE TITLE
Recently used sounds at the top of sound picker

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#148]
> User sortable alert sounds or favorites that move to top of list.  I find that I use 5 sounds over and over.  I would like to select these from the top of the list when creating new tasks. 

This feature is actually available on iOS, but I'd assumed that it's not that difficult to use the keyboard to search for the sound on macOS, hence it was not prioritised.

**Comment by honcheng** [comment]
Feature is implemented, and may be out in 21.9
