### ISSUE TITLE
Suggestion: Update the popup behaviour triggered when doing due:///add?title=

### ISSUE THREAD

**Issue by sortofworks** [dueapp/Due-macOS#15]
There's a difference in behaviour between the old and new app when using `due:///add?title=`. I propose bringing back the old behaviour, as it requires fewer and easier keyboard usage.

#### After triggering Due with `due:///add?title=Remind me to X in 2 hours`

**Old behaviour** 
1. Due App is opened
1.  _'in 2 hours'_  is selected _and_ this time is now detected already automatically set in Due
1. I press the Delete key (to remove _'in 2 hours'_ from the title)
1. I press the Enter key to confirm and close the dialog

The Delete and Enter keys are easy to access

**New behaviour**
1. Due App is opened
1.  _'in 2 hours'_  is detected but _not_ selected, time is _not_ set in Due at this point
1. I reach and press the Left arrow key to trigger a popup menu
1. I reach and press CMD+1 to set time and remove it from the title
1. I press the Enter key to confirm and close the dialog

The Left arrow key and CMD+1 are not as easy to access

**Proposed updated compromise** 🙂 
1. Due App is opened
1.  _'in 2 hours'_  is detected, and the existing popup menu **is already displaying**
1. I press CMD+1 to set time and remove it from the title
1. I press the Enter key to confirm and close the dialog
---
### Alfred App

<img src="https://user-images.githubusercontent.com/5196997/88757535-9848d200-d166-11ea-9f75-0f1e8c4bbb1b.jpg" alt="Your image title" width="250" />

### Triggers
`due:///add?title=check Due on Github in 2 hours`

### Due App's 'add modal' is opened:
<img src="https://user-images.githubusercontent.com/5196997/88758356-8b2ce280-d168-11ea-9362-afce2daa2ade.jpg" alt="Your image title" width="300"  />

### Press the Left arrow key
<img src="https://user-images.githubusercontent.com/5196997/88758359-8cf6a600-d168-11ea-98dd-b6dfc89e343b.jpg" alt="Your image title" width="300"/>

**Comment by junjie** [comment]
Thanks for the request and suggestion @andynil.

@honcheng we may need to rerun the checks on whether to display the popover at the caret in this scenario.That said, I do notice that in some languages a parseable date can be at the front, or in the middle of a string.  In such a case this would not work well for these languages either.

A possible solution could be to expand the [URL scheme](https://www.dueapp.com/developer.html) to include a parameter for date parsing (`parse`?) with the options equivalent to the popup:

1. `setremove`
2. `setkeep`
3. `ignore`

If users always want to parse and remove dates, they could set up the URL scheme accordingly, e.g.

`due://x-callback-url/add?title=Remind%20me%20to%20X%20in%202%20hours&parse=setremove`

**Comment by honcheng** [comment]
> we may need to rerun the checks on whether to display the popover at the caret in this scenario

That should not be an issue. If parseable date and the caret are at the end of the text, then it's a bug that the popup does not appear. 

> I do notice that in some languages a parseable date can be at the front, or in the middle of a string

Just to clarify this, if we try to move the caret to the position of the parseable date when the parseable date is not at the end of the text, it will most likely mess with the users' workflow. Do you think so? 

> A possible solution could be to expand the URL scheme to include a parameter for date parsing (parse?) with the options equivalent to the popup:

Ok. We can try that.

**Comment by honcheng** [comment]
The bug with existing popup menu not displayed when editor is opened with due:/// is now fixed, and will be out in 20.3. 

> A possible solution could be to expand the URL scheme to include a parameter for date parsing (parse?) with the options equivalent to the popup:

This other solution will be explored in future updates. #33

**Comment by junjie** [comment]
@honcheng turning on `prefBoolParsesMilitaryTime` in #8 seems to regress this fix.

I used: due://x-callback-url/add?title=Remind%20me%20to%20X%20in%202%20hours and in 2 hours was not highlighted.

Turning off `prefBoolParsesMilitaryTime` made it work.

**Comment by honcheng** [comment]
This is fixed now.

**Comment by junjie** [comment]
@andynil This should be addressed in 20.3, can you give it a try? Also, here's an updated Alfred workflow with updated icon: http://www.dueapp.com/extras/Due.alfredworkflow

**Comment by sortofworks** [comment]
@junjie Works great! Thanks for addressing the issue and releasing the tweak so quickly.
