### ISSUE TITLE
Expand Preferences > Default due date to allow setting a time

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#150]
> Any chance of a default due time being added to the programme?

> Is Due > Preferences > Default due date what you’re looking for?

> No, my reminders are all scheduled to appear at 9am each morning. Just wondering if it might be possible to set a specific default time.

Currently on macOS:

<img width="493" alt="CleanShot 2021-03-08 at 16 04 25@2x" src="https://user-images.githubusercontent.com/524420/110292310-f9535500-8027-11eb-98e9-54df762226d9.png">

On iOS:

![IMG_3103](https://user-images.githubusercontent.com/524420/110292335-007a6300-8028-11eb-86fd-660e09c528a0.PNG)

**Comment by vitorgalvao** [comment]
I’ve been thinking of this for weeks and was about to open an issue on it. Didn’t know about the option on iOS, and effectively I’d like the same on macOS. I’ve added a 👍 to the top post. Is there another way you’d rather we show “I also want this”?

**Comment by junjie** [comment]
@vitorgalvao 👍🏼 is fine, though we get notifications when you leave a comment, so I'd say both!
