### ISSUE TITLE
Theme not switching automatically with system settings - persistent in dark mode

### ISSUE THREAD

**Issue by jpmanon** [dueapp/Due-macOS#151]
Theme does not change with the system and stays in dark mode.

Deactivating / reactivating, closing / opening app, or rebooting Mac does not solve issue.

Running on a Mac mini M1 (Apple Silicon) - macOS Big Sur 11.2.3 (20D91)

**Comment by junjie** [comment]
Hi I think it's related to #137. If so you can expect a fix in 21.1. Thanks
