### ISSUE TITLE
If Postpone by… is mapped to a keyboard shortcut without modifier key, the postpone overlay never dismiss and the postponing does not get triggered

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#156]
Related to #134 again.

For example:

<img width="567" alt="CleanShot 2021-03-24 at 16 15 14@2x" src="https://user-images.githubusercontent.com/524420/112276851-222c4900-8cbc-11eb-8a1d-52b6908dfa49.png">

I believe it is because we're depending on the keyboard shortcut having a modifier key, where releasing the modifier key commits the postponing and dismisses the overlay.

We should prioritise this

**Comment by honcheng** [comment]
I've made it such that without the expected modifier keys, it will use a 0.4s delay to accumulate changes before dismissing the view. Do you think that's sufficient?

**Comment by junjie** [comment]
For the information on the overlay to be useful, I think it needs to stay on longer. I've increased delay to 1s, with options to cancel with Escape key and confirm with Return key.
