### ISSUE TITLE
Changing the repeat option in custom repeat editor causes custom repeat editor to lose focus

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#157]
![Changing Custom Repeat Loses Keyboard Focus-Compressed-0001](https://user-images.githubusercontent.com/524420/112419449-670cba00-8d66-11eb-8e88-7fee669bc32a.png)
![Changing Custom Repeat Loses Keyboard Focus-Compressed-0002](https://user-images.githubusercontent.com/524420/112419453-683de700-8d66-11eb-9aa5-f0caf547c43c.png)

https://user-images.githubusercontent.com/524420/112419471-70962200-8d66-11eb-93d3-24b9e2929a66.mp4

**Comment by honcheng** [comment]
Fixed, will be out in 21.2.
