### ISSUE TITLE
New "Postpone" overlay should show day of week

### ISSUE THREAD

**Issue by mrw** [dueapp/Due-macOS#164]
Hello! It would be great if the new "postpone" overlay (screenshot attached) showed the day of the week. I'm often using that to decide when I want to postpone the item to (for example, next weekend). I know "+x days" should let me calculate it, but having the day of week there would make it easier and faster.

Thank you for your consideration!

<img width="985" alt="Screenshot%20on%202021-04-11%20at%2009-25-41" src="https://user-images.githubusercontent.com/50996/114305869-f1178b00-9aa7-11eb-90cd-1bffae4e3023.png">

**Comment by junjie** [comment]
Thanks @mrw, I think it'd be useful too!
