### ISSUE TITLE
Postponing a reminder with editor opened should also display the postpone overlay

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#168]
Currently when using the postpone by 10 minutes/1 hour/1 day shortcuts when editing a reminder (i.e. the editor is opened for the reminder), it:

1. adds the time inline, if there are unsaved changes made in the editor #161, or
2. immediately closes the editor and postpones the reminder by the amount of time, if there are no changes made in the editor #29

This bug relates to scenario 2.

Because it immediately postpones the reminder after closing the editor, I do not see the postpone overlay. If I press Cmd-= thrice, the first time would immediately close the window and postpone the reminder. The next 2 presses would result in the postpone overlay accumulating just 20 minutes of postponement.

Ideally it should dismiss the editor, then perform the postponing by showing the overlay, allowing me accumulate further postponement until I let go of the modifier key.

**Comment by honcheng** [comment]
Actually it causes a more severe bug. Subsequent keyboard action actually postpones the wrong reminder because the reminder in the editor is already moved elsewhere. Postpone actions from the 2nd keystroke onwards is passed on to the newly selected reminder. 

It should behave as your expected now.

**Comment by junjie** [comment]
Thanks, let me leave this open and run some tests
