### ISSUE TITLE
Return key in timer editor creates new line instead of triggering the default button (Save)

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#17]
It should attempt to save if the save button is button is enabled (i.e. hrs, mins, secs is not 0).

If not, perhaps we should make hrs first responder?

**Comment by honcheng** [comment]
This is fixed in 20.2, next update. 

If there are changes and changes can be saved (countdown is not 0), return key will save it.
Else it will make hrs the first responder.
