### ISSUE TITLE
Show/Hide Window shortcut recorder control placeholder text is too long and gets truncated in German

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#170]
![CleanShot 2021-06-11 at 11 43 04@2x](https://user-images.githubusercontent.com/524420/121627950-eb8bf080-caaa-11eb-9494-6a8f06bd2d5c.png)

English for comparison:

![CleanShot 2021-06-11 at 11 45 45@2x](https://user-images.githubusercontent.com/524420/121628069-1d9d5280-caab-11eb-855b-af7827396840.png)

@honcheng I think we are using the default localization in the 3rd-party framework?

**Comment by honcheng** [comment]
Yes

**Comment by junjie** [comment]
And Japanese too:

![CleanShot 2021-06-11 at 12 04 30@2x](https://user-images.githubusercontent.com/524420/121629174-37d83000-caad-11eb-9311-e245a05da970.png)

**Comment by honcheng** [comment]
![CleanShot 2021-06-11 at 13 57 50@2x](https://user-images.githubusercontent.com/208827/121638216-2d259700-cabd-11eb-8c6e-32370c8ee2de.png)

**Comment by honcheng** [comment]
@junjie don't have a shorter string for ja
