### ISSUE TITLE
Clicking notification results in corrupt duplicate items and missing overdue items

### ISSUE THREAD

**Issue by russelldavis** [dueapp/Due-macOS#171]
Quitting and then restarting the app fixes the problem. This has happened to me a bunch of times. Here's what happened on the latest one:

I had multiple notifications from Due. I clicked 'Done' on one of them. Then I clicked the body of the other one which brough the Due app to the foreground. Here's what it showed:

<img width="735" alt="Screen Shot 2021-06-12 at 10 04 41 AM" src="https://user-images.githubusercontent.com/551404/122132589-f1a60800-cdef-11eb-8142-9f6b4f89aebc.png">

Here's what it showed after restarting the app:

<img width="741" alt="Screen Shot 2021-06-12 at 10 06 19 AM" src="https://user-images.githubusercontent.com/551404/122132647-1306f400-cdf0-11eb-9576-55e318ad437c.png">

Notice in the first screenshot:
- The overdue items are missing
- The first two upcoming items are duplicated. The duplicate of 'Finalize Hawaii Stuff' incorrectly shows 'in 1h' even though the absolute time of '10:30 AM' is the same as the other copy, which correctly shows 'in 26m'.

I have screenshots from another time it when it did the same thing, with missing overdue items and corrupted duplicate items. I can send those over as well if it's helpful.

**Comment by huwan** [comment]
Same issue here. Need to manually restart Due app to fix it.

**Comment by junjie** [comment]
Thanks @russelldavis and @huwan 

I got in touch with @russelldavis to get some logs for diagnosis. Will update when we have more information about this bug.

**Comment by junjie** [comment]
Good news, @honcheng managed  to track down the issue. We'll be able to include that in the upcoming 21.4 update.

**Comment by russelldavis** [comment]
Amazing, thank you! 🎉
