### ISSUE TITLE
Mark Done does not work on "Reminder snoozed" notification.

### ISSUE THREAD

**Issue by honcheng** [dueapp/Due-macOS#185]
I'm not sure if it's related to this, #106, or something completely new, but I've noticed lately that "Mark Done" tends to work on a "Reminder due" notification, but it doesn't usually work on a "Reminder snoozed" notification. I'm not sure if it's the first auto-snoozed alert that stops working or if it has to have been snoozed some amount of times for the broken behavior to start.

_Originally posted by @augmentedfourth in https://github.com/dueapp/Due-macOS/issues/107#issuecomment-967148306_

**Comment by honcheng** [comment]
User have "menu bar only" mode turned on. This may or may not be related.

**Comment by goochisan** [comment]
﻿My tasks haven’t been syncing between iOS and macOS since early this morning. 

— John

**Comment by junjie** [comment]
> My tasks haven’t been syncing between iOS and macOS since early this morning. — John

@goochisan Please send an email through Due > Help > Email (on iOS), and Due > Help > Email Support… (macOS) for your issue, thanks.

**Comment by honcheng** [comment]
I'm able to replicate the issue in 21.4. But version 21.6 released shortly after this report already contain a fix for the issue. Closing the issue now.
