### ISSUE TITLE
Links in expanded notification not styled according to theme

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#187]
> Just a note that this is actually possible with a recent update for Notification Snooze. Expanding the notification will highlight links that are clickable.
> 
> ![CleanShot 2021-11-22 at 22 49 10@2x](https://user-images.githubusercontent.com/524420/142882077-3351d282-95e1-4dec-a1f7-3e0bb0141be9.png)

_Originally posted by @junjie in https://github.com/dueapp/Due-macOS/issues/162#issuecomment-975604877_

**Comment by junjie** [comment]
In dark mode, the notification follows the Pure Black color scheme, but the link 'apple.com' is not styled according to Pure Black theme.

<img width="423" alt="CleanShot 2021-11-24 at 11 39 50@2x" src="https://user-images.githubusercontent.com/524420/143170937-fe7ee98e-9646-404d-8bc2-7fa72cf81f99.png">

**Comment by junjie** [comment]
Light appearance notification content:
<img width="375" alt="CleanShot 2021-11-24 at 11 50 27@2x" src="https://user-images.githubusercontent.com/524420/143171701-361bb105-8c8a-4c2d-916e-4a66d5675163.png">

Vanilla Lilac theme:
<img width="436" alt="CleanShot 2021-11-24 at 11 49 38@2x" src="https://user-images.githubusercontent.com/524420/143171719-02f175b9-c33b-408c-a8ff-975350969c2d.png">

**Comment by honcheng** [comment]
We'll start using global accent colour in future updates
