### ISSUE TITLE
Press Quick Create hotkey to dismiss Quick Create panel

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#192]
> 特性支持: 再按一次快捷键取消快速创建而不是用esc
> Feature support: Press the shortcut key again to cancel the quick creation instead of using esc 

@honcheng: I remember we briefly explored whether to support this behaviour, but decided not to?

**Comment by honcheng** [comment]
I don't remember why we dropped it. But I think we can still proceed. So if there are changes, we'll just prompt them before dismissing.

**Comment by junjie** [comment]
I'm wondering whether the behaviour of toggling the same hotkey should mean 'Save' or 'Dismiss'. I looked at Things, and it means Save by default. The way you're looking at it (and how I'm thinking about it), we'd do dismiss if the same hotkey is triggered right?

**Comment by honcheng** [comment]
> The way you're looking at it (and how I'm thinking about it), we'd do dismiss if the same hotkey is triggered right?

Yes

**Comment by junjie** [comment]
I think we can assume Cancel by default, rather than Save.

**Comment by honcheng** [comment]
Ok. Will be out in 22.0.
