### ISSUE TITLE
Shortcuts integration fails when not run from inside Shortcuts app

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#196]
This has started happening a while back. At first I thought it was caused by an update in Shortcuts, but after several tests it may be Due-related. I’m not sure. [Here’s a dead-simple Workflow](https://github.com/dueapp/Due-macOS/files/7893622/Due.Reminder.shortcut.zip):

<img src=https://user-images.githubusercontent.com/1699443/150052279-3181667f-b011-4c87-90ed-c2f301db9a36.jpeg width=40%>

Install it and (on iOS) `Add to HomeScreen` or (on macOS) run from the command-line (`shortcuts run "Due Example"`). The result will be that you will be asked to input some text. After `Done`, the Shortcuts app will open and rerun the shortcut from the beginning, asking for the text again. It is this one which will continue to Due.

This is a simple example. My original Workflow does more things but the result is the same: as soon as it get to the step where Due should open, the Shortcuts app opens instead and the shortcut starts over, ignoring everything from the previous run.

Worth noting this hasn’t always been the case. Months ago it worked correctly, i.e. it only ran once from outside the Shortcuts app.

**Comment by junjie** [comment]
Hi @vitorgalvao, are you having trouble with this on iOS or macOS?

There was a related issue related to Shortcuts for macOS #194 

I'm not sure if that is related, but we did solve #194 in 22.0.

Also, the 'Add Reminder' shortcut is not actually provided by us, but was built in by Apple, a legacy from the Workflow era. It uses x-callback-url.

On iOS I'd recommend using the Create Reminder or Create Repeating Reminder shortcut, rather than the Add Reminder shortcut: https://dueapp.zendesk.com/hc/en-us/articles/360042468832-Using-Siri-Shortcuts-to-Add-Reminders-to-Due

**Comment by vitorgalvao** [comment]
> are you having trouble with this on iOS or macOS?

Both.

> I'm not sure if that is related, but we did solve #194 in 22.0.

Doesn’t fix this one.

> On iOS I'd recommend using the Create Reminder or Create Repeating Reminder shortcut, rather than the Add Reminder shortcut

But I use the shortcut on both, and that doesn’t work on macOS. Plus, *I want Due to open* so I can manually choose the date. I was able to make it work by calling `due://`, though it requires ugly workarounds to Shortcut strangenesses. Your comment about the feature I was using having been auto-added by Apple helped.

You can consider this a feature request for a working `Add Reminder` (no auto-added by Apple) or close it since I’ve solved my use case. Whichever you prefer.

**Comment by junjie** [comment]
Thanks Vitor, I'd look into filing a bug report with Apple about this

**Comment by vitorgalvao** [comment]
If you do and post here the details, I’ll make a duplicate (allegedly that makes them prioritise it).
