### ISSUE TITLE
Accept 'Enter' key wherever 'Return' key is accepted

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#197]
> Btw, would it be alright if I added another tiny request? Currently on the Mac app, we are unable to use the small ’ENTER’/‘RETURN’ key located next to the Numpad. So everytime after we input a time using the Numpad, we have to stretch our fingers over to hit the ‘ENTER/RETURN’ key in the middle of the keyboard.
> 
> I know it sounds a little nitpicky, but would it also be possible to add that functionality? Would really be a game changer!

The Return key and Enter key are actually two separate keys.  The key on the numpad is Enter, the key above Shift is Return. They usually perform two different functions https://daringfireball.net/2020/07/return_and_enter

But for many purpose people consider them the same, and we can support using 'Enter' where 'Return' is accepted.

For example:

1. Accepting a date suggestion
2. Saving a reminder

Credit: Aaron P.

**Comment by honcheng** [comment]
Done. Will be out in a future update.
