### ISSUE TITLE
Too easy to accidentally trigger docking to menu bar when positioning Due window on a smaller screen, with Show Icon in: Menu Bar enabled

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#2]
![Too Easy To Dock](https://user-images.githubusercontent.com/524420/88648438-91d04100-d0f9-11ea-985e-e3b5eeb2169a.gif)

On a smaller screen like a MacBook Pro, it can be easy to accidentally trigger the snap-and-dock mechanism to the menu bar icon.

We should look into the adjusting the threshold for snap-and-dock to menu bar.

**Comment by honcheng** [comment]
This has been tweaked, and will be included in the next 20.2 update.
