### ISSUE TITLE
Investigate if it's possible for upgrade pass demo banner to show for user who had updated their app with Show Icon In: Menu Bar Only

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#20]
https://twitter.com/jaime_jsola/status/1288421080189804544:

> Before updating I had Due in Menu Bar Only icon mode. Then I updated the app to v.20.1, and the Upgrade Pass banner showed until I change the icon to Dock Only (didn’t try both dock and menu bar). Quit the app and launched it again, turned to Menu Bar Only icon and is working

**Comment by honcheng** [comment]
I've checked. Upgrade pass banner is not linked to the **Show icon in** option. 

But in 20.1, docking to menu bar is too sensitive, and it was easy to accidentally dock the app, causing the banner to be shown. User may not have realised that docking have happened. Changing the option to **Dock only** forces undocking from menu bar, and hide the banner. The issue with accidental docking is addressed in #2 

Another possibility is accidental selection of multiple reminders. That is considered bulk editing, and would have trigger the banner to be shown. 

The rest of the features are not likely to be the cause of trigger.

**Comment by junjie** [comment]
Ok let's close this for now. We've only had one report so far.
