### ISSUE TITLE
Allow drag and drop of url into Due on Mac to create new Reminder

### ISSUE THREAD

**Issue by sambody** [dueapp/Due-macOS#210]
Feature request: to allow dragging and dropping a url from a browser (Firefox in my case) onto the Due window, which automaticallly creates a new Reminder AND adds the url as a clickable link. It makes it more easy to create a reminder with a url.

Right now, I have to create a new Reminder and then copy paste the url into it.

The default Mac Reminders app has this drag and drop feature, and I miss it. 

Thank you.

**Comment by honcheng** [comment]
@sambody the feature to create a reminder by dragging text/link to Due has already been available since 2020. I tested with Firefox just in case, and it works too (as well as with other browsers). 

Do you not see a + green button when you drag the link on top of Due?

**Comment by sambody** [comment]
I have tested again, and now it works. Not sure why it didn't work the first time. I cannot reproduce it.
So this can be closed.
Thanks.
