### ISSUE TITLE
Quick Access Times should not be presented when double-clicking on a search-to-create reminder

### ISSUE THREAD

**Issue by clindsay3** [dueapp/Due-macOS#217]
Typing "Call dead river and tell them that oct 13 works" gives me two options, one that uses oct 13 as the date, the other that leaves it in the reminder. Great.

However, double clicking on the option that leaves it in the reminder presents a quick access time prompt that uses Oct 13 as the date, which is not what I expected. Feels like a bug.

https://user-images.githubusercontent.com/227043/191389389-ba268d2c-c75d-42d7-bb74-30f57fd23638.mov

**Comment by junjie** [comment]
How embarrassing, thanks @chrisvasselli for highlighting this bug with a clear video! We'll get to fixing it.
