### ISSUE TITLE
Add 'Public Issue Tracker…' to Help menu

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#22]
![CleanShot 2020-07-30 at 15 16 50@2x](https://user-images.githubusercontent.com/524420/88892689-ce29ab80-d277-11ea-9fb9-b61a752389dd.png)

Text: Public Issue Tracker…
Opens URL to: https://github.com/dueapp/Due-macOS

Will need localization, so leave this open until it's completed.

**Comment by honcheng** [comment]
@junjie this is done, but pending localisation

**Comment by junjie** [comment]
Still waiting for localized strings
