### ISSUE TITLE
Wrong item being postponed in Quick Access Times

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#221]
> > However, I’m still seeing that sometimes it doesn’t register the correct item to postpone when I right click on it. I’m not 100% sure, but I think it might be because I’m right clicking on the window when it’s not in focus. I’ll keep an eye on that and see if I can replicate it.
> 
> Ok - yes, I’ve replicated this.
> 
> If I have an item selected (left click), and I right click on a different item, the item I right clicked on shows up correctly in the postponement popup dialog, but when I click off of it, the originally selected item is the one that gets postponed instead of the one I right clicked on.

**Comment by junjie** [comment]
Credit: Adam F.

**Comment by junjie** [comment]
> Due Mac 22.7 (8631) on Mac13,1 (12.6.0)
> en_US (English (United States))
> PrefAttachedToMenuBar = 0
> PrefShowIconIn = 0

**Comment by honcheng** [comment]
Thanks. We've found the problem. A fix will be included in the next update.
