### ISSUE TITLE
Optional setting that enables a confirmation prompt when quitting Due

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#230]
> Hello, I love Due on macOS but sometimes I accidentally quit the app when I'm done editing a reminder.
> 
> I'm emailing to request (the option for) a confirmation prompt when quitting the app that asks, "Are you sure you want to quit Due? Keep Due running in the menu bar to be alerted of reminders" or something like that. Or even copy Chrome's "Hold ⌘Q to Quit" feature.

I think this is simple and meaningful enough to prioritise for the next update since accidentally quitting Due would have a negative impact on the ability to receive notifications on the Mac.

**Comment by honcheng** [comment]
So this option fits at the bottom of General Preferences? 

Or is this a box that appears in the prompt to quit, and users choose not to get prompted again. And they have to go to Preferences to 'reset prompts'?

**Comment by junjie** [comment]
![CleanShot 2023-05-09 at 12 41 55@2x](https://user-images.githubusercontent.com/524420/236995981-1064ec90-3929-410c-a754-4f39b8c45d1b.png)

Better in Preferences > General so that existing users don't suddenly see a behaviour change and get the prompt. False by default.

**Comment by honcheng** [comment]
<img width="652" alt="CleanShot 2023-05-10 at 09 52 31@2x" src="https://github.com/dueapp/Due-macOS/assets/208827/c23f1f91-c5a2-4688-9f42-9da46465cfbb">
