### ISSUE TITLE
Due app crashes when clicking on quick access times on macOS Sonoma

### ISSUE THREAD

**Issue by huwan** [dueapp/Due-macOS#236]
Whenever I click on the quick access times such as the +1 hr/-1 hr button to change the task reminder time, the app crashes abruptly. I am currently using the latest beta version of macOS Sonoma (14.0 Beta (23A5276g)).

I understand that the app may not yet support Sonoma and this issue might be due to the compatibility issues between the app and the new operating system. However, I wanted to bring this issue to your attention for your reference. 

<img width="401" alt="SCR-20230622-kwzk-2" src="https://github.com/dueapp/Due-macOS/assets/1451009/e6c0b394-063e-4ce8-8c0d-ff8016228813">

**Comment by huwan** [comment]
Additionally, there is a minor issue with black rounded corners appearing on the bottom right and top right sides when selecting a reminder, as shown in the figure above.

**Comment by junjie** [comment]
@huwan this should be fixed in 23.4 that is just released
