### ISSUE TITLE
Move Show Reminders/Timers/Logbook from View menu to Windows menu

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#24]
Our 20.2 build was rejected for screenshots and this issue:

> Design Preamble
> 
> The user interface of your app is not consistent with the macOS Human Interface Guidelines.
> 
> Specifically, we found that when the user closes the main application window there is no menu item to re-open it.
> 
> Next Steps
> 
> It would be appropriate for the app to implement a Window menu that lists the main window so it can be reopened, or provide similar functionality in another menu item. macOS Human Interface Guidelines state that "The menu bar [a]lways contains [a] Window menu".
> 
> Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.

I asked the reviewer if they could proceed to approve the critical bug fix as we work on this, since this already existed. Reviewer seemed to say they're ok to proceed if we remove the last screenshot. We'll see.

Anyway, upon re-examining the macOS HIG, it seems like we could have placed Show Reminders/Timers/Logbook items in the wrong menu:

<img width="202" alt="CleanShot 2020-07-30 at 23 25 09@2x" src="https://user-images.githubusercontent.com/524420/88941736-f63afe00-d2bb-11ea-8c95-42899ba7394c.png">

According to the [HIG](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/):

> The View menu lets the user customize the appearance of an app’s windows.… The View menu doesn’t include menu items for navigating between or managing specific windows. Those functions are provided by the Window menu

It says this about the Window menu:

> The Window menu lets people navigate, organize, and manage an app’s windows. This menu doesn’t include menu items for customizing the appearance of windows. Those functions are provided by the View menu.

Some typical menu items under Window includes "Show Previous Tab" and "Show Next Tab", so I guess it makes sense that our Show Reminders/Timers/Logbook is moved to Window menu.

This should satisfy the reviewer's complaint about "when the user closes the main application window there is no menu item to re-open it."

So it seems like a better idea is to follow Tweetbot's implementation of the Window menu:

<img width="182" alt="CleanShot 2020-07-30 at 23 26 48@2x" src="https://user-images.githubusercontent.com/524420/88941915-2b475080-d2bc-11ea-918c-431a46652136.png">

This would however leave us with an empty View menu. I think we can put some stuff in there, but that is a story for another issue.

**Comment by junjie** [comment]
@honcheng, please review code in commit to see if the code checking for visibility, and the code to show window, is appropriate for docked and undocked. Thanks!

**Comment by junjie** [comment]
This was rushed into 20.2 after a long night of back-and-forth. But please check the above anyway, thanks

**Comment by honcheng** [comment]
> But please check the above anyway, thanks

All good
