### ISSUE TITLE
Add new items for View menu

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#25]
The fix from #24 leaves View menu empty. Instead of removing it completely, let's add specific items that "lets the user customize the appearance of an app’s windows" per HIG.

I think we can go with:

Increase Text Size
Decrease Text Size
\---
Theme
    - Vanilla Lilac
    - Slate Dark
    - Pure Black
    - Lavender

For Theme:

1. We're not providing 'Automatic Theme Switching' over here
2. We reflect the active theme with a checkmark
3. If the user changes a theme with Automatic Theme Switching enabled, they'll be switching the theme for the current system appearance.

Also, given that these are all premium features, we need to test that these brings up the appropriate paywall/demo banner when activated.

**Comment by junjie** [comment]
Localization completed.

**Comment by honcheng** [comment]
This is done, and will be out in 20.3
