### ISSUE TITLE
Up/down arrow keys to increment/decrement timer field

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#27]
User request:

> When editing reminders and having the focus in HRS/MINS/SEC field, I think it would be cool if up/down arrow keys changed the existing number by +1/-1 instead of moving the cursor to the beginning/end of the field.

**Comment by honcheng** [comment]
That's a great suggestion.

**Comment by honcheng** [comment]
@junjie once the value reaches the maximum value for the field, we should increase the next value by 1. For example, pressing up at 01m59s when cursor is at seconds should change the value to 02m00s, but still keeping the cursor at seconds.

**Comment by honcheng** [comment]
Done, and will be out in 20.3
