### ISSUE TITLE
Keyboard shortcuts to postpone by 10 mins/1 hour/1 day don't work in editor

### ISSUE THREAD

**Issue by augmentedfourth** [dueapp/Due-macOS#29]
Perhaps related to changes for #4 

In the old version of Due for Mac, I often clicked on a notification and, once the app came up with the reminder highlighted, used command-equals or command-shift-equals to snooze a different duration than the default auto snooze.

In the new version, clicking the notification title brings you to the editing interface for the reminder, with the cursor on the Due date field. The snooze hotkeys don't work in that state. Can the snooze hotkeys work after clicking the notification title? And perhaps dismiss the edit pane if they're used?

**Comment by augmentedfourth** [comment]
To be clear, this happens on both "Reminder due" and "Reminder snoozed" notifications.

**Comment by augmentedfourth** [comment]
I guess I can get around this by hitting Escape and *then* command-equals, but I'm not 100% sure that the notification that fired the alarm will always be the one selected/active when the app interface comes up. I'm pretty sure I've seen it come up with a different reminder selected at least once, but I can't seem to reproduce the conditions (and that may have been prior to my upgrade to 20.2).

**Comment by junjie** [comment]
Thanks for the feedback @augmentedfourth. The idea behind this was to focus on the parsing date field so you can type precisely the date you want to postpone to, or the relative amount of time you want to postpone by.

But supporting the postponing shortcuts (Cmd-=, Cmd-Shift-=, Cmd-Opt-Shift-=) sounds like something we should do too.

I'm not too sure about auto-dismissing the editor after the keyboard shortcut though. If someone would like to postpone by 3 hours, it'd be quite annoying that it is dismissed right after one Cmd-Shift-=.

At the same time, we should aim to reduce the friction involved in postponing a repeating reminder this way

I understand that these keyboard shortcuts when applied to a reminder in the list will just postpone a repeating reminder without prompting whether the user wants it this occurrence/all occurrences. If we want to leave the editor open and let the user confirm the postponing with the Return key, ideally we shouldn't prompt them about the this occurrence/all occurrence thing at all. This is probably a separate issue to address altogether, so I'll create a new issue for this portion.

For now @honcheng let's add support for changing the due date with keyboard shortcuts when the editor is open.

**Comment by augmentedfourth** [comment]
Closing the editor but making sure focus stays on the task will allow you to continue postponing with the shortcut. But, right now, it doesn't seem that the firing alert is always the one that's selected in the interface after you click on the notification.

It doesn't seem that the selection/focus is even on the due date consistently when clicking the notification. It looks like the cursor started there, but then something else happened immediately and took focus away.

It would be nice if "in 5m" or even "5m" were parsed. "in 5 minutes" is a little wordy, and not a quick keyboard entry.

**Comment by junjie** [comment]
@augmentedfourth If clicking on notification doesn't open the correct reminder, then it's a bug that needs to be addressed separately. We haven't encounter that so far so we'd need more concrete steps to reproduce the issue for us to be able to diagnose the problem. If you have more info for us to reproduce the problem, do let us know.

I think you're right about the postponing shortcut behaviour in the editor. It could very well just dismiss the editor and perform the postponing as if the editor was not there in the first place, which would keep the selection on the postponed reminder. @honcheng can we try that behaviour?

Thanks for the suggestion for the parser improvement, I'll create a new issue for that

**Comment by junjie** [comment]
@honcheng I just thought about the scenario where the user has already made changes in the editor. In this case, if we just dismiss the editor, they'll lose the changes. If we dismiss the editor and the prompt to save/discard comes up, that's also annoying.

One way is to disable the postponing shortcuts if editor has unsaved changes. Another way is to handle these shortcuts differently, such that they increment the due date in the editor. I'm inclined to the former option so that i's more consistent, with less changes needed for a release.

**Comment by augmentedfourth** [comment]
I've never seen it open the edit window on the wrong reminder. However, the highlighted/selected reminder is not always the same as the one with the edit window open. I've clicked on a notification and seen the correct edit window, but if I hit escape to dismiss that window, the recently-notified reminder isn't always the one that's highlighted/selected. I can't figure out the exact circumstances to reproduce, however.

**Comment by honcheng** [comment]
> I think you're right about the postponing shortcut behaviour in the editor. It could very well just dismiss the editor and perform the postponing as if the editor was not there in the first place, which would keep the selection on the postponed reminder.

> One way is to disable the postponing shortcuts if editor has unsaved changes. 

Yes that can work.
