### ISSUE TITLE
If timer is showing search results, switching away from Timers and back shows the wrong countdown for it

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#35]
1. List showing all reminders:
![CleanShot 2020-08-03 at 14 02 01@2x](https://user-images.githubusercontent.com/524420/89150787-ee1be080-d591-11ea-8215-59d26eb7fe54.png)

2. Search for "triage":
![CleanShot 2020-08-03 at 14 02 08@2x](https://user-images.githubusercontent.com/524420/89150792-f2e09480-d591-11ea-8ff5-ad2f7ffa9b01.png)

3. Switch away and back to timers:
![CleanShot 2020-08-03 at 14 02 16@2x](https://user-images.githubusercontent.com/524420/89150796-f4aa5800-d591-11ea-8904-224a10345485.png)

Note that it seems to be showing the cell for Kettlebell HIIT although it uses the title for "Triage GitHub Issues".

Also there's a bug in step 2 where search results don't update a timer that is counting down.

**Comment by honcheng** [comment]
The bug is fixed, and will be out in upcoming 20.3 update.
