### ISSUE TITLE
Reminder menu not disabled when editor for new item is present; only partially disabled when editing existing item

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#37]
The reminder menu should have been disabled when editor is present. (However, this may no longer be true with changes in #29)

This is partially true for editing an existing reminder:

![CleanShot 2020-08-03 at 16 47 22@2x](https://user-images.githubusercontent.com/524420/89164106-385c8c00-d5a9-11ea-836e-fb725bebe5a4.png)

Noticed that auto snooze menu is not disabled.

The menu is not disabled at all when the editor is opened to create a new reminder. This means that we can accidentally delete items in the list while editor is opened to create new reminder. This can happen when we press the Delete key when the prompt to Save/Discard is showing.

![CleanShot 2020-08-03 at 16 47 39@2x](https://user-images.githubusercontent.com/524420/89164292-7a85cd80-d5a9-11ea-8388-402eb73ded74.png)

**Comment by honcheng** [comment]
This fix for this was out early in 20.3
