### ISSUE TITLE
Cmd-Delete not working to Discard Changes in editor

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#38]
Appears to have regressed from an earlier issue in private tracker.

Do check both Reminder and Timer editor.

**Comment by honcheng** [comment]
Looks like button localisation key for "Discard Changes" needs to be "Don't Save". 
https://developer.apple.com/documentation/appkit/1540934-nsrunalertpanel

But a workaround is to set the keyEquivalent and keyEquivalentModifierMask manually. 
https://lists.apple.com/archives/cocoa-dev/2014/Jun/msg00081.html

Swift does not have escape character for backspace "\b", so we have to use "\u{08}"
https://stackoverflow.com/questions/22068308/detect-delete-key-using-uikeycommand
