### ISSUE TITLE
Undo-ing the resetting of a paused timer causes the timer to start running again

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#43]
![CleanShot 2020-08-04 at 12 28 36](https://user-images.githubusercontent.com/524420/89253133-53350c00-d64e-11ea-8b1b-790a0dfca022.gif)

**Comment by honcheng** [comment]
Undo resetting a paused timer was not a feature that is available in iOS, but this will be possible in the next Mac app update 20.5. 

When reset for a paused timer is undone, it will restore to the paused state together with the time left. 
When reset for a running timer is undone, it can be restored to 2 different states depending on time left, counting down from the original due time. If there's no time left, undo reset does not do anything. If there's still time left, it will be restored to running state, with time left count down from original due time.
