### ISSUE TITLE
Allow sections to expand/collapse by clicking on section header title, in addition to the disclosure arrow

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#44]

**Comment by honcheng** [comment]
Should it be the whole header?

**Comment by junjie** [comment]
I'd think so, but if the header is much larger than the visible text, then it may cause some false positives?

**Comment by honcheng** [comment]
I’ll restrict it to the height of the text, but spans the length of the
header?

**Comment by junjie** [comment]
Yes, something like this?
![CleanShot 2020-08-07 at 17 17 19@2x](https://user-images.githubusercontent.com/524420/89630518-16794700-d8d2-11ea-9c8a-2caf08416f68.png)

**Comment by honcheng** [comment]
Done for 20.4
