### ISSUE TITLE
Open first URL in the selected reminder with the right-arrow key

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#45]
https://appfigures.com/reviews/110046225Lb2xmgfv9Meer4SznHDjqRw:

> 右キーでのURLを開く機能 Function to open a URL with the right key
> 新バージョンすごい良いのですが、旧バージョンであった右キーでURLを開く機能がなくなってしまったことが唯一の不満です。
> できれば復活してもらえたら嬉しいです。
> The new version is great, but my only complaint is that the function to open the URL with the right key, which was in the old version, is gone.
> I'd be happy if it could be revived.

**Comment by junjie** [comment]
In the last version there was a function where the first URL would be populated in the Reminders menu, accessible via right-arrow key. We should restore that:

<img width="452" alt="CleanShot 2020-08-05 at 11 35 39@2x" src="https://user-images.githubusercontent.com/524420/89369156-e41fec00-d70f-11ea-9b70-23c0baa7392d.png">

<img width="578" alt="CleanShot 2020-08-05 at 11 36 09@2x" src="https://user-images.githubusercontent.com/524420/89369162-e71adc80-d70f-11ea-873d-dd19f433cfad.png">

When the reminder does not contain a URL, it shows nothing:

<img width="587" alt="CleanShot 2020-08-05 at 11 36 35@2x" src="https://user-images.githubusercontent.com/524420/89369221-0f0a4000-d710-11ea-829b-fa8b181a8b0b.png">

**Comment by honcheng** [comment]
Added to the next update, 20.4
