### ISSUE TITLE
German localization screenshots not using correct font for header

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#50]
Not sure how I missed this, but it's not using the slab serif font that English uses. Perhaps overridden with the CJK overrides:

<img width="561" alt="At a glance Light" src="https://user-images.githubusercontent.com/524420/89545336-cc428800-d835-11ea-9a83-c8071e3f30f9.png">

**Comment by junjie** [comment]
Sorry, realised this was a result of switching system languages without restarting. The work that is required is to update the App Store screenshots.

**Comment by honcheng** [comment]
<img width="451" alt="Screenshot 2020-08-07 at 9 25 22 AM" src="https://user-images.githubusercontent.com/208827/89598662-f32da800-d88f-11ea-8ee0-a0427df99cfb.png">

Suspect so too. So close?

**Comment by junjie** [comment]
No I need to fix it

— JJ
