### ISSUE TITLE
File > New Item wrongly disabled when there is no item in reminders/timers, disabling Cmd-N shortcut

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#52]
<img width="756" alt="CleanShot 2020-08-07 at 07 17 29@2x" src="https://user-images.githubusercontent.com/524420/89592114-68907d00-d87e-11ea-91ec-658136d4d061.png">
<img width="748" alt="CleanShot 2020-08-07 at 07 17 39@2x" src="https://user-images.githubusercontent.com/524420/89592117-6af2d700-d87e-11ea-844a-5d630ffca510.png">

<img width="756" alt="CleanShot 2020-08-07 at 07 18 06@2x" src="https://user-images.githubusercontent.com/524420/89592133-75ad6c00-d87e-11ea-9ada-70c9e9e7432d.png">
<img width="745" alt="CleanShot 2020-08-07 at 07 17 49@2x" src="https://user-images.githubusercontent.com/524420/89592136-76de9900-d87e-11ea-8b6f-de36f8a562d9.png">

Only the + button in the sidebar works to create a new item, if there is no existing item in the list.

Tested on 20.3.

**Comment by honcheng** [comment]
Fixed in the next update, 20.4
