### ISSUE TITLE
Wrong reminder selected when clicking on notification of a reminder that moved from Today to Overdue

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#53]
To reproduce:
Make sure there is no overdue reminders, or at least, there is no overdue section.
Create a new reminder 1 min later.
Hide Due, wait for notification.
Click on notification.

Expected:
Reminder that fired the notification is selected

Actual:
The wrong reminder was selected. It appears to be selecting the old position, today section row 0?

Video:
https://safe.dsh.re/download/c52a7cd5-ea9c-4b7b-b63d-ef39b4f51e0d

**Comment by junjie** [comment]
This has potentially serious implication, leading a user to mark or postpone a reminder wrongly. Here's a video showing how a reminder "Feed Pepper" was due. Clicked on the notification, it opens the editor correctly, but yet the list selects the wrong reminder "Fruits". At this point, a menu item action, like Mark Done, would have acted on Fruits instead of Feed Pepper.

Video reproduction: https://safe.dsh.re/download/74ae7d41-b773-4f77-b676-56a21d86adc6

Reproducible on Version 20.3 (6062)

Upgrading status to critical bug.

**Comment by honcheng** [comment]
Ok. This is fixed now for the next 20.4 update
