### ISSUE TITLE
Reset menu item should be enabled for a running timer as well

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#55]
![CleanShot 2020-08-07 at 13 17 19@2x](https://user-images.githubusercontent.com/524420/89611682-62b38f80-d8b0-11ea-8306-1f1a8a7bbdf1.png)

![CleanShot 2020-08-07 at 13 18 08@2x](https://user-images.githubusercontent.com/524420/89611722-77902300-d8b0-11ea-9bd3-7e240e571eef.png)

This way they can turn off a timer in one shot, without first pausing it.

**Comment by honcheng** [comment]
This will be enabled in 20.4
