### ISSUE TITLE
Enable prefBoolParsesMilitaryTime by default

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#57]
> This would need more testing to ensure that it doesn't break existing changes. We'll be including the changes in 20.3, but it must be enabled with the following command in Terminal.app:
> 
> `defaults write com.phocusllp.duemac prefBoolParsesMilitaryTime -bool YES`
> 
> for the behaviour to kick in. Once it is stable, we'll roll it out for 20.4.

_Originally posted by @junjie in https://github.com/dueapp/Due-macOS/issues/8#issuecomment-667890281_

If testers have no issues, we can deprecate the preference and make it default by 20.4

**Comment by honcheng** [comment]
Done. Will be out in 20.4

**Comment by honcheng** [comment]
This change is removed from default because it causes problem with year parsing.
