### ISSUE TITLE
Notifications without having the app open?

### ISSUE THREAD

**Issue by vitorgalvao** [dueapp/Due-macOS#60]
Apple Reminders can show notifications while the app isn’t open. Would that be viable with Due?

**Comment by junjie** [comment]
Thanks for the suggestion.

That would involve scheduling notifications in advance, which is what we do on iOS. There is a lot of restrictions with the Notifications API, including a limit of 64 notifications, inability to repeat a notification at the interval required for auto snooze to work, etc.

In addition, this would pose additional challenges with syncing. If the app is not actively running, it'll not be able to perform the changes to reschedule/cancel notifications when changes are made to the database. I don't believe the [background notifications API](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app) work on the Mac. But even if they are, they are unpredictable on iOS as it is.

I'd not want the Mac app to have to deal with all these issues that we already face on iOS, so is not something we're considering.

**Comment by vitorgalvao** [comment]
Thought as much. Thank you for the clarification and thorough reply.
