### ISSUE TITLE
Show Preferences icon in side bar when Show icon in: Menu Bar Only

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#7]
https://twitter.com/tarrkid/status/1288108129989931009

Currently we show the settings cog when the app is docked to the menu bar. However, it appears that many have switched Show Icon In: to Menu Bar Only, without attaching Due to the menu bar icon.

This means they have no way to access menu bar Due > Preferences to switch it back.

I suggest we always show the settings cog whenever the user is in menu bar only mode, regardless of the docking status.

**Comment by honcheng** [comment]
> I suggest we always show the settings cog whenever the user is in menu bar only mode, regardless of the docking status.

Oops. Overlooked this. 
It is fixed now. Will be available in the 20.2 update.
