### ISSUE TITLE
Embedded URL Follow shortcut

### ISSUE THREAD

**Issue by jshelton** [dueapp/Due-macOS#71]
In previous Due.app version, typing the right arrow key (as a single key keyboard shortcut) would visit the embedded url. This has tremendous use in automation. Please add this in the current version.

As a side note, the way that it works in iOS works very well giving you the option to visit the URL when completing a task. 

Thank you!

**Comment by junjie** [comment]
Thanks, this is implemented with #45 and will be available in 20.4.

**Comment by junjie** [comment]
@jshelton 20.4 is out with this fix
