### ISSUE TITLE
If right-arrow fails to open a link in reminder without a link, selecting another reminder with a link will not open the link the first time you pressed the right-arrow key

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#74]
Reproduction:
1. Select a reminder without a link
2. Press right arrow key to attempt to open link
3. You'll hear a system error beep emitted because there is no link
4. Select another reminder with a link
5. Press the right arrow key

Expected:
Right-arrow key opens the link in the reminder

Actual:
Right-arrow key triggers the system error beep for the reminder with link as well.

Notes:
The second time the right-arrow key is pressed, it works as expected.
If right-arrow key was not first triggered on a reminder without a link, it works as expected.

Related: #45

**Comment by honcheng** [comment]
Fixed for next update 20.5
