### ISSUE TITLE
Hiding the Sidebar/Making it Smaller

### ISSUE THREAD

**Issue by joshbahk** [dueapp/Due-macOS#79]
Right now I feel like the sidebar is way too big. I like using the app as the smallest possible window and thus it takes up about 20%-ish of the space available. I want to be able to hide the sidebar, or at least make it smaller. Hiding the sidebar would be the best option considering that I don't use the timer feature very often. It would be nice to have a simple command that would let you hide and show the sidebar again.

**Comment by junjie** [comment]
Thanks for the feedback, we've plans for that: #40
