### ISSUE TITLE
Parse 24-hour time without colon (e.g. 1100 instead of 11:00)

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#8]
https://twitter.com/bjkirton/status/1288103623503646721:

> Ben Kirton
> @bjkirton
> Replying to @dueapp
> Downloaded. Purchased. Awesome.
> 
> First bug/feature though: can 24hr time be made available without the :? “tomorrow 1100” is easier and (I think) more obvious to type than “tomorrow 11:00”

**Comment by junjie** [comment]
https://twitter.com/_jacobsa_/status/1288316635200147456:

> Aaron Jacobs
> @_jacobsa_
> Replying to @dueapp
> Thanks! Another one: my muscle memory for writing “0730” or “1645” for the time no longer works; I have to remember to add a colon.

**Comment by junjie** [comment]
@honcheng: One idea to try could be to run a regex for `(\d\d)(\d\d)`, manually inserting a colon in between `\1` and `\2` before feeding it to the parser. It could potentially break existing parsing, so any change would need further testing.

**Comment by jacobsa** [comment]
For what it's worth, this used to work before the update. That's what I meant about my muscle memory in the comment above: I keep getting this wrong because I'm used to not needing a colon. I assume it's particularly annoying for pilots, but not sure how important a market segment that is for you. :-)

**Comment by honcheng** [comment]
> One idea to try could be to run a regex for (\d\d)(\d\d), manually inserting a colon in between \1 and \2 before feeding it to the parser. It could potentially break existing parsing, so any change would need further testing.

I'm using `([0-1][0-9]|2[0-4])[0-5][0-9]` and it's working out well. 

There are 2 locations where text are parsed to dates. In the due date text field, supporting this should not be an issue. It is more tricky in the title view, where we have to parsed the replaced text, but underline the original non-replaced text.

**Comment by junjie** [comment]
> > One idea to try could be to run a regex for (\d\d)(\d\d), manually inserting a colon in between \1 and \2 before feeding it to the parser. It could potentially break existing parsing, so any change would need further testing.
> 
> I'm using `([0-1][0-9]|2[0-4])[0-5][0-9]` and it's working out well.
> 
> There are 2 locations where text are parsed to dates. In the due date text field, supporting this should not be an issue. It is more tricky in the title view, where we have to parsed the replaced text, but underline the original non-replaced text.

I think we need to go with `\b([0-1][0-9]|2[0-3])[0-5][0-9]\b`

There are 60*24 = 1,440 possible minutes, and it should match 1,440 times in a list from 0000-10000.

The result is here: https://regexr.com/59asp

The regex in your post would match 1501 times, because it matches 2400-2459. It also matches 0000 in 10000, so we need the word boundaries `\b`.

**Comment by junjie** [comment]
> For what it's worth, this used to work before the update. That's what I meant about my muscle memory in the comment above: I keep getting this wrong because I'm used to not needing a colon. I assume it's particularly annoying for pilots, but not sure how important a market segment that is for you. :-)

![Screenshot 2020-07-30 at 12 57 19 PM](https://user-images.githubusercontent.com/524420/88882386-69b12100-d264-11ea-8761-87cab123f175.png)

@jacobsa: The issue here is that the older version had 2 fields, one for date and one for time. It's relatively easy to assume that whatever you've keyed into the time field can be parsed as a time, even just "13" can be interpreted as 13:00.

**Comment by jacobsa** [comment]
Right, I see. Personally I was totally fine with two fields.

**Comment by jjlharrison** [comment]
I am a new user of the Mac app (been using the iOS app for years though) and this has been the only annoyance I’ve had really. I’m not a pilot, but I do often write times in this format. I appreciate the complexity, but I’d love it if this could be fixed.

**Comment by honcheng** [comment]
<img width="526" alt="Screenshot 2020-07-30 at 3 09 49 PM" src="https://user-images.githubusercontent.com/208827/88892028-bb62a700-d276-11ea-8895-e5f7000cad83.png">

Some progress. This part is more straight forward. We are showing results of text that have been changed to include colon. 

The parser can't tell AM/PM from 0100 to 1200 and just assumes the next nearest occurrence. But time after 1300 are parsed as PM. So aside from inserting colon in the parsing text, we may want to insert AM if it is before 1200 to force AM in the result.

**Comment by junjie** [comment]
Thanks! As I understand, 0000-1159 is unambiguously AM in 24-hour speak. One solution to address the issue is as you've suggested, feeding in AM to the parser.

But I feel like we're fighting the parser this way. Another way is to write a custom 24-hour parser that has a go at these times. I think we can have better and more consistent result parsing 4 digits than trying to wring the existing parser to do this.

If we're going the custom parser route, we may be able to look at the parser that does relative time as a reference to its implementation.

**Comment by honcheng** [comment]
<img width="526" alt="Screenshot 2020-07-30 at 3 16 10 PM" src="https://user-images.githubusercontent.com/208827/89100462-b560f780-d429-11ea-8eb1-a75d05faba8a.png">

This is more tricky. The typed text is 1800, but the parsed text is 18:00 after inserting colon. But after parsing, I converted the detected range of the new text back to the original text. This is a more straightforward scenario. There'll be more scenarios to test. i.e. when there are multiple time that are replaced. 

But it's good progress so far.

**Comment by junjie** [comment]
This would need more testing to ensure that it doesn't break existing changes. We'll be including the changes in 20.3, but it must be enabled with the following command in Terminal.app:

`defaults write com.phocusllp.duemac prefBoolParsesMilitaryTime -bool YES`

for the behaviour to kick in. Once it is stable, we'll roll it out for 20.4.

**Comment by junjie** [comment]
@honcheng: The changes appears to have affected relative date parsing. All relative dates are no longer parsed when this is enabled.

![CleanShot 2020-08-03 at 16 45 59@2x](https://user-images.githubusercontent.com/524420/89163841-d1d76e00-d5a8-11ea-89bb-4bbc2a570f16.png)

**Comment by honcheng** [comment]
This is fixed now. The range converter only converted ranges where the parsed results are dates. But relative date parsing's results are string. Now if they are not dates, they will be kept without changes.

**Comment by junjie** [comment]
@jacobsa @jjlharrison: We pushed out an experimental fix in 20.3, which can be enabled with the steps here: https://github.com/dueapp/Due-macOS/issues/8#issuecomment-667890281

Can you try out the fix?

**Comment by jacobsa** [comment]
Sorry for the slow response. Seems to work for me, thanks!
