### ISSUE TITLE
Pause menu item should become Stop, and should work to stop+reset timer once a timer with autosnooze expires

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#80]
<img width="450" alt="CleanShot 2020-08-20 at 22 25 11@2x" src="https://user-images.githubusercontent.com/524420/90784650-15193700-e334-11ea-8a76-3372de137eae.png">

Currently Pause doesn't do anything. Reset is disabled as well.

If Pause becomes Stop, effectively it does the same thing as Reset.

However for the sake of using the same keyboard shortcut Cmd-S to stop the timer, let's just keep them both in there.

**Comment by honcheng** [comment]
Will be fixed in the next update, 20.5
