### ISSUE TITLE
Increase max number of days/weeks/months/years for repeat

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#83]
Currently maxes at 30 on iOS side.

At the data layer this is fully supported. Only the UI level needs to change to support this behaviour.

And both iOS and macOS will need to be updated.

When this value increases, it means it can also be applied to larger calendar units like week, months, years. I guess that was one of the reason why it was kept low like 30, where after 30 days people could go to months. But it doesn't work if someone wants every 45 days.

But even right now, a reminder 30 years sounds a bit crazy. Calendar supports up to 999. I've only heard of requests until 365 days I think. But I guess no harm supporting 999?

![IMG_0674](https://user-images.githubusercontent.com/524420/90850133-76c4ba00-e3a3-11ea-85c2-018636c0d2b2.PNG)

**Comment by junjie** [comment]
Works fine on iOS:

![E87E2B8A-3569-41B9-955F-8A2FF5467F21](https://user-images.githubusercontent.com/524420/90851138-606c2d80-e3a6-11ea-9b6c-aba388eacce2.JPG)

**Comment by honcheng** [comment]
This will be added in the next update, 20.5
