### ISSUE TITLE
Show icon in: Menu bar only mode ends up showing dock icon after clicking on a notification

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#84]
No concrete repro steps yet, but I can confirm that it has happened for me.

**Comment by bluecursor** [comment]
Happens to me on every scheduled event. Very annoying!

**Comment by junjie** [comment]
Do you mean it happens when a reminder becomes due?

**Comment by bluecursor** [comment]
When you check Mark done is when it happens, the Dock Icon shows back up. Have to go back into settings and reset menubar only.

Frank Michielli
Sent with iOS Spark!📱

**Comment by junjie** [comment]
Thanks @bluecursor!

@honcheng can you check?

**Comment by honcheng** [comment]
> When you check Mark done is when it happens, the Dock Icon shows back up. Have to go back into settings and reset menubar only. 

@bluecursor Can I check, when you say **reset** to menubar only, did the option in Preference change to another option your dock icon shows up?

**Comment by bluecursor** [comment]
No it does not change. Have to select something else and then Change it back to menu at only

Frank Michielli
Sent with iOS Spark!📱

**Comment by honcheng** [comment]
The fix for this will be out in the next update, 20.5. 
Thanks!
