### ISSUE TITLE
Resetting a timer (that is not the last timer) with the timer page scrolled to the bottom, unexpectedly scrolls the list

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#85]
![CleanShot 2020-08-26 at 12 54 50](https://user-images.githubusercontent.com/524420/91257028-72c9db00-e79b-11ea-9048-86d4249bb1bb.gif)

**Comment by honcheng** [comment]
Will be out in the next update, 20.5

**Comment by junjie** [comment]
This is still happening on 20.5-6201:

![Due-85](https://user-images.githubusercontent.com/524420/91725640-9d6bc780-ebd1-11ea-97ca-d575ba59845c.gif)

**Comment by honcheng** [comment]
Fixed for 20.5
