### ISSUE TITLE
How to downgrade to previous version?

### ISSUE THREAD

**Issue by tedmiston** [dueapp/Due-macOS#9]
Hi -

I appreciate the dev effort in revitalizing the macOS app, but the bright purple and very opinionated themes and subscription pass screens everywhere are not for me.

I would like to just continue using the simpler original Due app version that I purchased previously; however the MAS automatically upgraded me to this new version.

Where can we find the previous version to downgrade?

**Comment by junjie** [comment]
Hi,

The App Store does not support rolling back updates. As Due is exclusively distributed through the App Store at the moment, I'm afraid there's no way to downgrade to an older version.

**Comment by sortofworks** [comment]
I find the update a bit of a mixed bag.

I'm really glad to see there being development on the mac app again, thanks!

Junjie, as you mention on your blog (?), the old UI looked dated. But that was the only negative in my mind. It was clean and not visually distracting, quick to load and navigate.

Anyone who liked the "un-distracting" UI of the old app is now _forced_ to pay for an upgrade to get a semblance back of this: making the font size smaller, get the UI back to using one colour gradient, only the dark mode has that option now. I'm all for a Dark mode, I use it mostly everywhere. However, I don't want "my" Due in Dark mode, unfortunately, I'm also not a fan of Light mode's purple left sidebar. Ideally, you'd offer a light mode as clean as the old app, or the option to completely hide/show the left sidebar.

**Comment by junjie** [comment]
Thanks, now that the overhauled app is shipped, we're happy to be able to work on more frequent updates for the Mac too. (The old code was so unwieldy we have trouble getting it to compile on modern Xcode.)

We've approached this redesign and overhaul in a manner that we felt was best for the app, just as we had when I made the first version.

It was certainly not our goal to make a version that we thought was worse off, so that we can "force" customers to pay such that they can make it look like the older version.

In an ideal scenario, the look and feel would resonate with every customer. Unfortunately that almost never happens in the real world, especially when it comes to things like design that have certain amount of subjectivity.

It's a delicate balance that we try to strike in any redesign.

**Comment by tedmiston** [comment]
Hi @junjie - This is a really tricky situation.  As a customer I am really disappointed by this response.

I bought a product, the product was changed abruptly overnight without warning after ~3? years of being stable and the same.  Functionality was removed and large ads for subscription banners are now presented.

According to your response, I can no longer run the version that I permanently purchased as a one-time transaction and have been using daily for years because the company is refusing to distribute access to it.  I purchased the software to own it for life — removing it without warning with a silent auto upgrade was a very unwelcome surprise.

If you had instead launched Due v2 as a separate MAS app, then ongoing users would not have to deal with this issue... my thoughts on the new UX are very similar to @andynil 's, but design opinions aside, we did purchase the app indefinitely.

I don't see mentioned in the terms (https://dueapp.com/terms.html) about removing access to previously purchased software.  If "you can no longer use the software you previously purchased" is the path forward, please just issue me a refund for now.

Thank you.

**Comment by jjlharrison** [comment]
@tedmiston: You have purchased the app from Apple, not the developer. It is also Apple that are responsible for not allowing access to older versions. With regard to terms, the sale of the app is also sold under the terms of the App Store. The developer is unable to offer refunds, you'd need to take it up with Apple.

**Comment by junjie** [comment]
@tedmiston I disagree that the update has taken away functionality or access to your previously purchased software, or whether the app should be a new app, etc. We can argue about it, but I sense from your messages that this will get us no where. As mentioned by James, developers do not handle your payments on the App Store. Apple does not provide us with any data of our customers. If you'd like you get a refund, contacting Apple would be your best recourse.

Finally, if you're extremely committed to using the particular version of the app that you have purchased, and not having apps "silent auto upgrade" "without warning", perhaps you should consider turning off Automatic Updates in App Store > Preferences > Automatic Updates.

![Screenshot 2020-07-31 at 12 07 11 PM](https://user-images.githubusercontent.com/524420/88999203-7433ef00-d326-11ea-904e-743d9d0761fa.png)

This setting is disabled by default on a fresh install of Mojave and Catalina.

Another thing that could have helped would be to have backups of your computer. You'll be able to roll back to a previous version of an app by just dragging the app from your backup back to /Applications.

**Comment by sortofworks** [comment]
> It was certainly not our goal to make a version that we thought was worse off so that we can "force" customers to pay such that they can make it look like the older version.

@junjie I'm sorry, I don't believe that, and it certainly wasn't my intention to sound like you were trying to force customers to pay for an upgrade. I understand that the app is in a much better place today with the underpinnings restructured and rebuilt to enable you to move faster with updates in the future. I would have made the same decision.
