### ISSUE TITLE
First launch window size is too narrow, and positioned awkwardly to the left

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#90]
This is what it looks like:

![01](https://user-images.githubusercontent.com/524420/91723060-c38f6880-ebcd-11ea-90ef-92a0f09d23f4.jpg)

![02](https://user-images.githubusercontent.com/524420/91723066-c7bb8600-ebcd-11ea-8dc0-2be26cf74372.jpg)

It should probably look more like this, centralized:

![03](https://user-images.githubusercontent.com/524420/91723104-d86bfc00-ebcd-11ea-86bb-ad6291018b04.jpg)

![04](https://user-images.githubusercontent.com/524420/91723110-dace5600-ebcd-11ea-8934-dbd973209c4c.jpg)

**Comment by honcheng** [comment]
This is fixed now. Will be out in 20.5
