### ISSUE TITLE
Scrollbar has grey background colour in Reminders view

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#92]
![CleanShot 2020-09-02 at 20 58 07](https://user-images.githubusercontent.com/524420/91985511-0d5b8880-ed5f-11ea-952a-c87359a82847.gif)

Show scroll bars: Always
<img width="471" alt="CleanShot 2020-09-02 at 20 59 53@2x" src="https://user-images.githubusercontent.com/524420/91986319-4267db00-ed5f-11ea-95fc-74cd9f4831cc.png">

They should behave like Timers/Logbook view.

Same thing for other themes. Except Lavender which seems to have a grey background colour for all views instead of following the theme's background.

**Comment by junjie** [comment]
<img width="394" alt="CleanShot 2020-09-02 at 21 02 08@2x" src="https://user-images.githubusercontent.com/524420/91986679-94a8fc00-ed5f-11ea-93a3-19fed0d6ef02.png">

<img width="393" alt="CleanShot 2020-09-02 at 21 02 31@2x" src="https://user-images.githubusercontent.com/524420/91986733-a8ecf900-ed5f-11ea-97ed-8206ddf4d88f.png">

For Lavender and Pure Black, the background is present for all views. Pure Black seems to have a different background color in Timers/Logbook vs Reminders.

<img width="401" alt="CleanShot 2020-09-02 at 21 02 58@2x" src="https://user-images.githubusercontent.com/524420/91986755-b1ddca80-ed5f-11ea-81e1-21f0cd8aad41.png">

<img width="399" alt="CleanShot 2020-09-02 at 21 01 53@2x" src="https://user-images.githubusercontent.com/524420/91986652-8b1f9400-ed5f-11ea-96b9-205253a109e5.png">

**Comment by honcheng** [comment]
Fixed, and should be ready in 20.6
