### ISSUE TITLE
Can search field be highlighted when using Show/Hide shortcut?

### ISSUE THREAD

**Issue by sonbarke** [dueapp/Due-macOS#93]
When pressing the 'Show/Hide Window' shortcut key to show the Due window, can the cursor be set on the 'Search' field? It would be great to start typing a new 'Due' reminder without having to select the 'Search' field with the mouse.

OR as an alternative, perhaps a keyboard shortcut to select the 'Search' field when the Due window is open.

**Comment by junjie** [comment]
Hi,

Sorry I got back to your email late. In any case, there is a keyboard shortcut you can use to highlight the search field. Cmd-F brings it to the search field. Cmd-N brings up an editor to create a new reminder. Does that resolve your problem?

**Comment by sonbarke** [comment]
Yes -- thank you. I looked for the keyboard shortcut, but should've thought about the Mac convention of using Cmd-F!

I'll proceed with closing the comment. Thanks!
