### ISSUE TITLE
Due does not prevent app from quitting when there is a pending upload

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#99]
Due 1.x used to do that. If there is a pending upload (e.g. just marked a reminder complete), attempting to quit Due would:

1. trigger sync immediately
2. put up a modal sheet with a progress bar about sync progress
3. offer buttons to quit immediately, or cancel
4. quit Due automatically when upload succeeds, or
5. quit Due after a time-out when upload fails.

Right now, Due just quits, and the changes the user make would not be uploaded until the next time the user launches Due on the Mac again.

**Comment by honcheng** [comment]
@junjie this is done, but pending localisation

**Comment by junjie** [comment]
@honcheng: If I disable network while the prompt is in progress, I get this:

![96076242-71857680-0edf-11eb-91a8-99ff6a633404](https://user-images.githubusercontent.com/524420/96076380-cd4fff80-0edf-11eb-874d-1b4d4cf3437b.png)

It quits automatically shortly after, and this is the correct behaviour.

However, if I relaunch Due and attempt to quit again (with the network still disabled), I get stuck here:

![96076215-5adf1f80-0edf-11eb-91fb-20e463f5499a](https://user-images.githubusercontent.com/524420/96076440-ec4e9180-0edf-11eb-8f49-dc91a91f2d64.png)

It does not seem to detect that there is no network, and to display the error message and quit automatically shortly after, as above.

On top of that, if network connectivity returns, this prompt stays stuck here. Of course, if we had quit earlier once we hit an error with no network connectivity, then we don't have to handle this.
